<?php use Phalcon\Tag; ?>
<?php echo $this->getContent(); ?>
<?php $this->partial("commun/titre", array("titre" =>"Sources entitée")) ?>
<?php $this->partial("commun/search_entete") ?>

<table class="table table-striped table-search">
    <thead>
        <tr>
            <th class="id">Id</th>
            <th>URL</th>
            <th>Organisme responsable</th>
            <th><?php echo $this->tag->linkTo("igo_source_entite/search?order=date_modif", "Date de modification <span class='glyphicon glyphicon-resize-vertical'></span>") ?></th>
            <th class="actions"></th>
         </tr>
    </thead>
    <tbody>
    <?php foreach ($page->items as $igo_source_entite) { ?>
        <tr>
            <td><?php echo $igo_source_entite->id ?></td>
            <td><?php echo $igo_source_entite->url ?></td>
            <td><?php if ($igo_source_entite->IgoOrganismeResponsable) { echo $igo_source_entite->IgoOrganismeResponsable->nom;} ?></td>
            <td><?php echo $igo_source_entite->date_modif ?></td>
            <td class="overflow-visible"> 
                <div class="dropdown">
                    <button class="btn btn-default dropdown-toggle" type="button" id="dropdown-actions" data-toggle="dropdown" aria-expanded="true">
                        Actions
                        <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
                        <li><?php echo $this->igo_tag->linkIfAdmin(array("igo_source_entite/edit/" . $igo_source_entite->id."/".$r_controller."/".$action."/".$parameters, "<span class='glyphicon glyphicon-pencil' aria-hidden='true'></span> Modifier")); ?></li>
                        <li><?php echo $this->igo_tag->linkIfAdmin(array("igo_source_entite/delete/" . $igo_source_entite->id."/".$r_controller."/".$action."/".$parameters, "<span class='glyphicon glyphicon-trash' aria-hidden='true'></span> Détruire", 'data-confirmation'=>'supprimer')); ?></li>
                    </ul>
                </div>
            </td>
        </tr>
    <?php } ?>
    </tbody>
</table>
<?php $this->partial("commun/search_pagination") ?>