<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="url">URL</label>
    </div>
    <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
        <?php echo $this->tag->textField(array(
                "url", 
                "class" => "form-control"
            )); 
        ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="organisme_responsable_id">Organisme responsable</label>
    </div>
    <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
        <?php echo $this->tag->select(array(
                "organisme_responsable_id", 
                IgoOrganismeResponsable::find(array("order" => "nom")), 
                "using" => array("id", "nom"), 
                "emptyText" => "Choisir...",
                "class" => "form-control",
                "useEmpty" => true
            )); 
        ?>
    </div>
</div>

<?php $this->partial("commun/date_modification"); ?>