<?php use Phalcon\Tag; ?>
<?php echo $this->getContent(); ?>
<?php $this->partial("commun/titre", array("titre" =>"Connexions")) ?>
<?php $this->partial("commun/search_entete") ?>

<table class="table table-striped table-search">
    <thead>
        <tr>
            <th class="id"><?php echo $this->tag->linkTo("igo_connexion/search?order=id", "Id<span class='glyphicon glyphicon-resize-vertical'></span>") ?></th>
            <th><?php echo $this->tag->linkTo("igo_connexion/search?order=nom", "Nom <span class='glyphicon glyphicon-resize-vertical'></span>") ?></th>
            <th class="connexion">Connexion</th>
            <th>Type</th>
            <th class="date_modif"><?php echo $this->tag->linkTo("igo_connexion/search?order=date_modif", "Date de modification <span class='glyphicon glyphicon-resize-vertical'></span>") ?></th>
            <th></th>  
        </tr>
    </thead>
    <tbody>
    <?php foreach ($page->items as $igo_connexion) { ?>
        <tr>
            <td><?php echo $igo_connexion->id ?></td>
            <td><?php echo $igo_connexion->nom ?></td>
            <td><pre><?php echo $igo_connexion->connexion;?></pre></td>
            <td><?php if ($igo_connexion->IgoConnexionType) { echo $igo_connexion->IgoConnexionType->nom;} ?></td>
            <td><?php echo $igo_connexion->date_modif ?></td>
            <td class="overflow-visible"> 
                <div class="dropdown">
                    <button class="btn btn-default dropdown-toggle" type="button" id="dropdown-actions" data-toggle="dropdown" aria-expanded="true">
                        Actions
                        <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
                        <li><?php echo $this->tag->linkTo(array("igo_connexion/edit/" . $igo_connexion->id."/".$r_controller."/".$action."/".$parameters, "Éditer")); ?></li>
                        <li><?php echo $this->tag->linkTo(array("igo_connexion/delete/" . $igo_connexion->id."/".$r_controller."/".$action."/".$parameters, "Détruire", 'data-confirmation'=>'supprimer')); ?></li>
                       </ul>
                </div>
            </td>
        </tr>
    <?php } ?>
    </tbody>
</table>
<?php $this->partial("commun/search_pagination") ?>