
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="nom">Nom</label>
    </div>
    <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
        <?php echo $this->tag->textField(array(
                "nom", 
                "class" => "form-control"
            )); ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="connexion">Connexion</label>
    </div>
    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
        <?php echo $this->tag->textArea(array(
                "connexion", 
                "cols" => 100, 
                "rows" => 20, 
                "class" => "form-control"
            )); ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="connexion_type_id">Type de connexion<span class="glyphicon glyphicon-asterisk oblig"></span></label>
    </div>
    <div class="col-lg-2 col-md-3 col-sm-4 col-xs-12">
        <?php echo $this->tag->select(array(
                "connexion_type_id",
                IgoConnexionType::find(array("order" => "nom")),
                "using" => array("id", "nom"),
                "emptyText" => "Choisir...",
                "useEmpty" => true,
                "class" => "form-control"
            ));
        ?>
    </div>
</div>
<?php $this->partial("commun/date_modification"); ?>
