<?php use Phalcon\Tag; ?>
<?php echo $this->getContent(); ?>
<?php $this->partial("commun/titre", array("titre" =>"Liste de valeurs")) ?>
<?php $this->partial("commun/search_entete") ?>

<table class="table table-striped">
    <thead>
        <tr>
            <th><?php echo $this->tag->linkTo("igo_liste_valeur/search?order=id", "Liste de valeur") ?></th>
            <th><?php echo $this->tag->linkTo("igo_liste_valeur/search?order=description", "Description") ?></th>
            <th><?php echo $this->tag->linkTo("igo_liste_valeur/search?order=date_modif", "Date de modification") ?></th>
         </tr>
    </thead>
    <tbody>
    <?php foreach ($page->items as $igo_liste_valeur) { ?>
        <tr>
            <td><?php echo $igo_liste_valeur->id ?></td>
            <td><?php echo $igo_liste_valeur->description ?></td>
            <td><?php echo $igo_liste_valeur->date_modif ?></td>
            <td><?php echo $this->tag->linkTo(array("igo_liste_valeur/edit/" . $igo_liste_valeur->id."/".$r_controller."/".$action."/".$parameters, "Editer")); ?></td>
            <td><?php echo $this->tag->linkTo(array("igo_liste_valeur/delete/" . $igo_liste_valeur->id."/".$r_controller."/".$action."/".$parameters, "Détruire", 'data-confirmation'=>'supprimer')); ?></td>
        </tr>
    <?php } ?>
    </tbody>
</table>
<?php $this->partial("commun/search_pagination") ?>