<?php use Phalcon\Tag; ?>

<?php echo $this->getContent(); ?>
    

<?php echo $this->tag->form() ?>

<?php $this->partial("commun/titre", array("titre" =>"Associer des groupes de couches")) ?>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Id groupe</th>
            <th>Type</th>
            <th>Nom</th>
            <th>Ind. fond de carte</th>
            <th>Visible</th>
            <th>Active</th>

         </tr>
    </thead>
    <tbody>
    <?php foreach ($page->items as $row) {  ?>
        <tr>
            <td><?php echo $row->groupe_id ?></td>
            <td><?php echo $row->nom ?></td>
            <td><?php echo $row->description ?></td>
            <td><?php echo $this->tag->textField(array("ind_fond_de_carte_".$row->groupe_id."_".$row->id,"value" => $row->ind_fond_de_carte, "size" => 1)) ?></td>
            <td><?php echo $this->tag->checkField(array("est_visible_".$row->groupe_id."_".$row->id, "value" => 1, $row->est_visible?"checked":"unchecked" => 1)) ?></td>
            <td><?php echo $this->tag->checkField(array("est_active_".$row->groupe_id."_".$row->id, "value" => 1, $row->est_active?"checked":"unchecked" => 1)) ?></td>
            <td><?php echo $this->tag->linkTo(array("igo_couche_contexte/edit/" . $row->id."/".$controller."/".$action."/".$parameters, "<span class='glyphicon glyphicon-pencil' aria-hidden='true'></span> Modifier")) ?></td>
        </tr>

    <?php } ?>  
        <tr>
            <td><?php echo $this->tag->submitButton("Sauver") ?></td>
        </tr>
    </tbody>
     <?php if ($page->total_pages>1) { ?>
    <tbody>
        <tr>
            <td colspan="2" align="right">
                <table align="center">
                    <tr>
                        <td><?php echo $this->tag->linkTo("igo_couche/search", "Premier") ?></td>
                        <td><?php echo $this->tag->linkTo("igo_couche/search?page=" . $page->before, "Précédent") ?></td>
                        <td><?php echo $this->tag->linkTo("igo_couche/search?page=" . $page->next, "Suivant") ?></td>
                        <td><?php echo $this->tag->linkTo("igo_couche/search?page=" . $page->last, "Dernier") ?></td>
                        <td><?php echo $page->current, "/", $page->total_pages ?></td>
                    </tr>
                </table>
            </td>
        </tr>
    <tbody>
    <?php } ?>
</table>
