<?php use Phalcon\Tag; ?>
<?php echo $this->getContent(); ?>
<?php $this->partial("commun/titre", array("titre" =>"Groupes de couche")) ?>
<?php $this->partial("commun/search_entete") ?>

<table class="table table-striped table-search">
    <thead>
        <tr>
            <th class="id"><?php echo $this->tag->linkTo("igo_groupe/search?order=id", "Id<span class='glyphicon glyphicon-resize-vertical'></span>") ?></th>
            <th><?php echo $this->tag->linkTo("igo_groupe/search?order=nom", "Nom <span class='glyphicon glyphicon-resize-vertical'></span>") ?></th>
            <th><?php echo $this->tag->linkTo("igo_groupe/search?order=description", "Description <span class='glyphicon glyphicon-resize-vertical'></span>") ?></th>
            <th>Exclu du navigateur</th>
            <th>Groupe parent</th>
            <th><?php echo $this->tag->linkTo("igo_groupe/search?order=profil_proprietaire_id", "Propriétaire ID <span class='glyphicon glyphicon-resize-vertical'></span>") ?></th>
            <th class="date_modif"><?php echo $this->tag->linkTo("igo_groupe/search?order=date_modif", "Date de modification <span class='glyphicon glyphicon-resize-vertical'></span>") ?></th>
            <th class="actions"></th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($page->items as $igo_groupe) { ?>
        <tr>
            <td><?php echo $igo_groupe->id ?></td>
            <td><?php echo $igo_groupe->nom ?></td>
            <td><?php echo $igo_groupe->description ?></td>
            <td><?php if($igo_groupe->est_exclu_arbre){?>
                    <span class="glyphicon glyphicon-ok color-green"></span>
                <?php }?>
            </td>  
            <td><?php
                    if ($igo_groupe->parents){
                        foreach ($igo_groupe->parents as $parent){
                            echo $parent->nom . "<br>";
                        }
                    } 
                ?>
            </td>
            <td><?php echo $igo_groupe->profil_proprietaire_id ?></td>
            <td><?php echo $igo_groupe->date_modif ?></td>
            <td class="overflow-visible"> 
                <div class="dropdown">
                    <button class="btn btn-default dropdown-toggle" type="button" id="dropdown-actions" data-toggle="dropdown" aria-expanded="true">
                        Actions
                        <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
                        <li><?php echo $this->igo_tag->linkIfProprietaire(array("igo_groupe/edit/" . $igo_groupe->id."/".$r_controller."/".$action."/".$parameters, "<span class='glyphicon glyphicon-pencil' aria-hidden='true'></span> Modifier"), $igo_groupe->profil_proprietaire_id); ?></li>
                        <li><?php echo $this->igo_tag->linkIfProprietaire(array("igo_groupe/delete/" . $igo_groupe->id."/".$r_controller."/".$action."/".$parameters, "<span class='glyphicon glyphicon-trash' aria-hidden='true'></span> Détruire", 'data-confirmation'=>'supprimer'), $igo_groupe->profil_proprietaire_id); ?></li>
                    </ul>
                </div>
            </td>
        </tr>
    <?php } ?>
    </tbody>
</table>
<?php $this->partial("commun/search_pagination") ?>