<?php
$estAdmin = $this->session->get("info_utilisateur")->estAdmin;
?>

<?php echo \Phalcon\Tag::javascriptInclude("js/jquery/multiselect.min.js"); ?>
<?php echo \Phalcon\Tag::javascriptInclude("js/selecteurGaucheDroite.js"); ?>
<?php echo \Phalcon\Tag::javascriptInclude("js/gestion_couche_creation.js"); ?>
<script>
$(document).ready(function(){
    
    if($('#multiselect_groupe_to option').length > 0){
        $('#specifier_groupe_couche').trigger('click');
    }
});
</script>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="nom">Nom<span class="glyphicon glyphicon-asterisk oblig"></span></label>
    </div>
    <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
        <?php echo $this->tag->textField(array(
                "nom", 
                "class" => "form-control"
            )) ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="description">Description</label>
    </div>
    <div class="col-lg-4 col-md-5 col-sm-6 col-xs-12">
        <?php echo $this->tag->textField(array(
                "description", 
                "class" => "form-control"
            )) ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="est_exclu_arbre">Exclu du navigateur</label>
    </div>
    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
        <?php echo $this->tag->checkField(array("est_exclu_arbre", "value" => 1)) ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="profil_proprietaire_id">Profil propriétaire<?php if(!$estAdmin):?><span class="glyphicon glyphicon-asterisk oblig"></span><?php endif;?></label>
    </div>
    <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
        <?php
	    echo $this->tag->select(array(
				        "profil_proprietaire_id",
					$estAdmin ? IgoProfil::find(array("order" => "libelle")) : IgoProfil::findAllProfils(),
					"using" => array("id", "libelle"),
					"emptyText" => "Choisir...",
					"useEmpty" => true,
					"class" => "form-control"
        				));
        ?>
    </div>
</div>
<?php if("edit" == $action || "new" == $action || "create" == $action):?>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="groupe_id">Groupe parents</label>
    </div>
    <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
        <?php
            echo IgoTag::selecteurGaucheDroite(array(
                'prefixe' => 'groupe_parent', 
                'listeDe' => $this->view->groupesPasParentsDeGroupe, 
                'listeA' => $this->view->groupesParentsDeGroupe
        ));
        ?>
    </div>
</div>
<?php endif;?>
<?php if("edit" == $action || "new" == $action || "create" == $action):?>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="">Enfants</label>
    </div>
    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
        <input type="radio" name="specifier" value="couche" data-toggle="ligne_couche_id" id="specifier_couche" <?php  echo $this->view->estGroupeDeCouche ? 'checked': ''; ?>><label for="specifier_couche">Couche</label><br>
        <input type="radio" name="specifier" value="groupe" id="specifier_groupe_couche" <?php  echo !$this->view->estGroupeDeCouche ? 'checked': ''; ?>><label for="specifier_groupe_couche">Groupe de couche</label>
    </div>
</div>
<div class="row" data-toggle="specifier_couche">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="couche_id">Couche<span class="glyphicon glyphicon-asterisk oblig"></span></label>
    </div>
    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
        
    <?php
    
        echo IgoTag::selecteurGaucheDroite(array(
                'prefixe' => 'couche_enfant', 
                'listeDe' => $this->view->couchesPasEnfantDeGroupe, 
                'listeA' => $this->view->couchesEnfantDeGroupe
        ));
      
    ?>
    </div>
</div>
<div class="row" data-toggle="specifier_groupe_couche">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="groupe_couche_id">Groupe de couches*</label>
    </div>
    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
    <?php
    
        echo IgoTag::selecteurGaucheDroite(array(
            'prefixe' => 'groupe_enfant', 
            'listeDe' => $this->view->groupesPasEnfantsDeGroupe, 
            'listeA' => $this->view->groupesEnfantsDeGroupe
        ));
     
     
    ?>
    </div>
</div>
<?php $this->partial("commun/date_modification"); ?>
<?php endif;?>