<?php use Phalcon\Tag; ?>
<?php echo $this->getContent(); ?>
<?php $this->partial("commun/titre", array("titre" =>"Attributs")) ?>
<?php $this->partial("commun/search_entete") ?>

<table class="table table-striped">
    <thead>
        <tr>
            <th><?php echo $this->tag->linkTo("igo_attribut/search?order=id", "Attribut") ?></th>
            <th>Géometrie</th>
            <th>Colonne</th>
            <th>Alias</th>
            <th><?php echo $this->tag->linkTo("igo_attribut/search?order=description", "Description") ?></th>
            <th>Clé</th>
            <th>Nom</th>
            <th>Description</th>
            <th>Filtre</th>
            <th>Géométrie</th>
            <th>Inclu</th>
            <th>Liste de valeur</th>
            <th><?php echo $this->tag->linkTo("igo_attribut/search?order=date_modif", "Date de modification") ?></th>
         </tr>
    </thead>
    <tbody>
    <?php foreach ($page->items as $igo_attribut) { ?>
        <tr>
            <td><?php echo $igo_attribut->id ?></td>
            <td><?php  if ($igo_attribut->IgoGeometrie){echo $igo_attribut->IgoGeometrie->IgoClasseEntite->nom.":".$igo_attribut->IgoGeometrie->IgoGeometrieType->nom;} ?></td>
            <td><?php echo $igo_attribut->colonne ?></td>
            <td><?php echo $igo_attribut->alias ?></td>
            <td><?php echo $igo_attribut->description ?></td>
            <td><?php $this->tag->setDefault("est_cle", $igo_attribut->est_cle);
                 echo $this->tag->checkField(array("est_cle", "value" => 1, "disabled" =>1)) ?></td>    
            <td><?php $this->tag->setDefault("est_nom", $igo_attribut->est_nom);
                 echo $this->tag->checkField(array("est_nom", "value" => 1, "disabled" =>1)) ?></td>    
            <td><?php $this->tag->setDefault("est_description", $igo_attribut->est_description);
                 echo $this->tag->checkField(array("est_description", "value" => 1, "disabled" =>1)) ?></td>
             <td><?php $this->tag->setDefault("est_filtre", $igo_attribut->est_filtre);
                 echo $this->tag->checkField(array("est_filtre", "value" => 1, "disabled" =>1)) ?></td>          
            <td><?php $this->tag->setDefault("est_geometrie", $igo_attribut->est_geometrie);
                 echo $this->tag->checkField(array("est_geometrie", "value" => 1, "disabled" =>1)) ?></td>    
            <td><?php $this->tag->setDefault("est_inclu", $igo_attribut->est_inclu);
                 echo $this->tag->checkField(array("est_inclu", "value" => 1, "disabled" =>1)) ?></td>


            <td><?php  if ($igo_attribut->IgoListeValeur){echo $igo_attribut->ListeValeur->description;} ?></td>
            <td><?php echo $igo_attribut->date_modif ?></td>
            <td><?php echo $this->tag->linkTo(array("igo_attribut/edit/" . $igo_attribut->id."/".$r_controller."/".$action."/".$parameters, "<span class='glyphicon glyphicon-pencil' aria-hidden='true'></span> Modifier")); ?></td>
            <td><?php echo $this->tag->linkTo(array("igo_attribut/delete/" . $igo_attribut->id."/".$r_controller."/".$action."/".$parameters, "<span class='glyphicon glyphicon-trash' aria-hidden='true'></span> Détruire", 'data-confirmation' => 'supprimer')); ?></td>
        </tr>
    <?php } ?>
    </tbody>   
</table>
<?php $this->partial("commun/search_pagination") ?>