<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="geometrie_id">Geometrie</label>
    </div>
    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
        <?php
        if ($this->session->has("geometrie_id")) {
            $this->tag->setDefault("geometrie_id", $this->session->get("geometrie_id"));
        }
        ?>
        <?php echo $this->tag->select(array(
                "geometrie_id", 
                IgoGeometrie::find(array("order" => "vue_defaut")), 
                "using" => array("id", "vue_defaut"), 
                "emptyText" => "Choisir...", 
                "useEmpty" => true
            ));
        ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="colonne">Colonne</label>
    </div>
    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
        <?php echo $this->tag->textField(array("colonne", "size" => 30)) ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="alias">Alias</label>
    </div>
    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
        <?php echo $this->tag->textField(array("alias", "size" => 30)) ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="description">Description</label>
    </div>
    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
        <?php echo $this->tag->textField(array("description", "size" => 30)) ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="est_cle">Clé</label>
    </div>
    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
        <?php echo $this->tag->checkField(array("est_cle", "value" => 1)) ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="est_nom">Nom</label>
    </div>
    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
        <?php echo $this->tag->checkField(array("est_nom", "value" => 1)) ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="est_description">Description</label>
    </div>
    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
        <?php echo $this->tag->checkField(array("est_description", "value" => 1)) ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="est_filtre">Filtre</label>
    </div>
    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
        <?php echo $this->tag->checkField(array("est_filtre", "value" => 1)) ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="est_geometrie">Géométrie</label>
    </div>
    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
        <?php echo $this->tag->checkField(array("est_geometrie", "value" => 1)) ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="est_inclu">Inclu</label>
    </div>
    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
        <?php echo $this->tag->checkField(array("est_inclu", "value" => 1)) ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="liste_valeur_id">Liste de valeur</label>
    </div>
    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
        <?php echo $this->tag->select(array(
                "liste_valeur_id", 
                IgoListeValeur::find(array("order" => "description")), 
                "using" => array("id", "description"), 
                "emptyText" => "Choisir...", 
                "useEmpty" => true)) ?>
    </div>
</div>
<?php $this->partial("commun/date_modification"); ?>