<?php use Phalcon\Tag; ?>
<?php echo $this->getContent(); ?>
<?php $this->partial("commun/titre", array("titre" =>"Contacts")) ?>
<?php $this->partial("commun/search_entete") ?>

<table class="table table-striped table-search">
    <thead>
        <tr>
            <th class="id"><?php echo $this->tag->linkTo("igo_contact/search?order=id", "Id<span class='glyphicon glyphicon-resize-vertical'></span>") ?></th>
            <th>Organisme responsable</th>
            <th><?php echo $this->tag->linkTo("igo_contact/search?order=prenom", "Nom <span class='glyphicon glyphicon-resize-vertical'></span>") ?>, <?php echo $this->tag->linkTo("igo_contact/search?order=nom", "Prénom&nbsp;<span class='glyphicon glyphicon-resize-vertical'></span>") ?></th>
            <th>Poste</th>
            <th>Téléphone</th>
            <th>Courriel</th>
            <th>Membre ACRIgéo</th>
            <th>Remarque</th>
            <th class="date_modif"><?php echo $this->tag->linkTo("igo_contact/search?order=date_modif", "Date de modification <span class='glyphicon glyphicon-resize-vertical'></span>") ?></th>
            <th></th>
         </tr>
    </thead>
    <tbody>
    <?php foreach ($page->items as $igo_contact) { ?>
        <tr>
            <td><?php echo $igo_contact->id ?></td>
            <td><?php if ($igo_contact->IgoOrganismeResponsable) { echo $igo_contact->IgoOrganismeResponsable->nom;} ?></td>
            <td><?php echo $igo_contact->nom ?>, <?php echo $igo_contact->prenom ?></td>
            <td><?php echo $igo_contact->poste ?></td>
            <td><?php echo $igo_contact->no_telephone ?></td>
            <td><?php echo $igo_contact->courriel ?></td>    
            <td><?php if($igo_contact->est_membre_acrigeo){echo '<span class="glyphicon glyphicon-ok color-green"></span>';}?></td>        
            <td><?php echo $igo_contact->remarque ?></td>
            <td><?php echo $igo_contact->date_modif ?></td>
            <td class="overflow-visible"> 
                <div class="dropdown">
                    <button class="btn btn-default dropdown-toggle" type="button" id="dropdown-actions" data-toggle="dropdown" aria-expanded="true">
                        Actions
                        <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
                        <li><?php echo $this->igo_tag->linkIfAdmin(array("igo_contact/edit/" . $igo_contact->id."/".$r_controller."/".$action."/".$parameters, "<span class='glyphicon glyphicon-pencil' aria-hidden='true'></span> Modifier")); ?></li>
                        <li><?php echo $this->igo_tag->linkIfAdmin(array("igo_contact/delete/" . $igo_contact->id."/".$r_controller."/".$action."/".$parameters, "<span class='glyphicon glyphicon-trash' aria-hidden='true'></span> Détruire", 'data-confirmation'=>'supprimer')); ?></li>
                    </ul>
                </div>
            </td>
        </tr>
    <?php } ?>
    </tbody>
</table>
<?php $this->partial("commun/search_pagination") ?>