
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="organisme_responsable_id">Organisme responsable</label>
    </div>
    <div class="col-lg-4 col-md-5 col-sm-6 col-xs-12">
        <?php
        echo $this->tag->select(array(
            "organisme_responsable_id",
            IgoOrganismeResponsable::find(array("order" => "nom")), "using" => array("id", "nom"),
            "emptyText" => "Choisir...",
            "useEmpty" => true, 
            "class" => "form-control"
            ));
        ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="prenom">Prénom<span class="glyphicon glyphicon-asterisk oblig"></span></label>
    </div>
    <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
        <?php echo $this->tag->textField(array(
                "prenom", 
                "class" => "form-control"
            )); 
        ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="nom">Nom<span class="glyphicon glyphicon-asterisk oblig"></span></label>
    </div>
    <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
        <?php echo $this->tag->textField(array(
                "nom", 
                "class" => "form-control"
            )); 
        ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="poste">Poste occupé</label>
    </div>
    <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
        <?php echo $this->tag->textField(array(
                "poste", 
                "class" => "form-control"
            )); 
        ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="no_telephone">Téléphone</label>
    </div>
    <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
        <?php echo $this->tag->textField(array(
                "no_telephone", 
                "class" => "form-control"
            )); 
        ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="courriel">Courriel</label>
    </div>
    <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
        <?php echo $this->tag->textField(array(
                "courriel", 
                "class" => "form-control"
            )); ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="est_membre_acrigeo">Membre ACRIgéo</label>
    </div>
    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
        <?php echo $this->tag->checkField(array(
                "est_membre_acrigeo", 
                "value" => 1
            )); 
        ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="remarque">Remarque</label>
    </div>
    <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
        <?php echo $this->tag->textField(array(
                "remarque", 
                "class" => "form-control"
            )); 
        ?>
    </div>
</div>
<?php if("edit" == $action):?>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="date_modif">Date de modification</label>
    </div>
    <div class="col-lg-2 col-md-2 col-sm-3 col-xs-12">
        <?php
        echo $this->tag->textField(array(
            "date_modif",
            "class" => "form-control",
            'readonly' => 'readonly',
            'disabled' => 'disabled'));
        ?>
    </div>
</div>
<?php endif;?>