<?php use Phalcon\Tag; ?>
<?php echo $this->getContent(); ?>
<?php $this->partial("commun/titre", array("titre" =>"Association utilisateur/profil")) ?>
<?php $this->partial("commun/search_entete") ?>

<table class="table table-striped table-search">
    <thead>
        <tr>
            <th id="id">Id</th>
            <th>Profil</th>
            <th>Utilisateur</th>
            <th>Date de modification</th>
            <th class="editer"></th>
            <th class="detruire"></th>  
         </tr>
    </thead>
    <tbody>
    <?php foreach ($page->items as $igo_utilisateur_profil) { ?>
        <tr>
            <td><?php echo $igo_utilisateur_profil->id ?></td>
            <td><?php echo $igo_utilisateur_profil->IgoProfil->libelle; ?></td>
            <td><?php echo $igo_utilisateur_profil->IgoUtilisateur->nom; ?></td>
            <td><?php echo $igo_utilisateur_profil->date_modif ?></td>
            <td><?php echo $this->tag->linkTo(array("igo_utilisateur_profil/edit/" . $igo_utilisateur_profil->id."/".$r_controller."/".$action."/".$parameters, "Editer")); ?></td>
            <td><?php echo $this->tag->linkTo(array("igo_utilisateur_profil/delete/" . $igo_utilisateur_profil->id."/".$r_controller."/".$action."/".$parameters, "Détruire", 'data-confirmation'=>'supprimer')); ?></td>
        </tr>
    <?php } ?>
    </tbody>
</table>
<?php $this->partial("commun/search_pagination") ?>
