<?php use Phalcon\Tag; ?>
<?php echo $this->getContent(); ?>
<?php $this->partial("commun/titre", array("titre" =>"Association utilisateur/profil")) ?>
<?php $this->partial("commun/search_entete") ?>

<table class="table table-striped table-search">
    <thead>
        <tr>
            <th class="id"><?php echo $this->tag->linkTo("igo_utilisateur_profil/search?order=id", "Id<span class='glyphicon glyphicon-resize-vertical'></span>") ?></th>
            <th>Profil</th>
            <th>Utilisateur</th>
            <th><?php echo $this->tag->linkTo("igo_utilisateur_profil/search?order=date_modif", "Date de modification <span class='glyphicon glyphicon-resize-vertical'></span>") ?></th>
            <th class="actions"></th>
         </tr>
    </thead>
    <tbody>
    <?php foreach ($page->items as $igo_utilisateur_profil) { ?>
        <tr>
            <td><?php echo $igo_utilisateur_profil->id ?></td>
            <td><?php echo $igo_utilisateur_profil->IgoProfil->libelle; ?></td>
            <td><?php echo $igo_utilisateur_profil->IgoUtilisateur->nom; ?></td>
            <td><?php echo $igo_utilisateur_profil->date_modif ?></td>
            <td class="overflow-visible"> 
                <div class="dropdown">
                    <button class="btn btn-default dropdown-toggle" type="button" id="dropdown-actions" data-toggle="dropdown" aria-expanded="true">
                        Actions
                        <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
                        <li><?php echo $this->tag->linkTo(array("igo_utilisateur_profil/edit/" . $igo_utilisateur_profil->id."/".$r_controller."/".$action."/".$parameters, "<span class='glyphicon glyphicon-pencil' aria-hidden='true'></span> Modifier")); ?></li>
                        <li><?php echo $this->tag->linkTo(array("igo_utilisateur_profil/delete/" . $igo_utilisateur_profil->id."/".$r_controller."/".$action."/".$parameters, "<span class='glyphicon glyphicon-trash' aria-hidden='true'></span> Détruire", 'data-confirmation'=>'supprimer')); ?></li>
                    </ul>
                </div>
            </td>
        </tr>
    <?php } ?>
    </tbody>
</table>
<?php $this->partial("commun/search_pagination") ?>
