<?php echo $this->getContent(); ?>

<?php echo $this->tag->form("mapfile/genere") ?>

<?php $this->partial("commun/titre", array("titre" =>"Générer un mapfile")) ?>

<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="contexte_id">Contexte</label>
    </div>
    <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
        <?php echo $this->tag->select(array(
                "contexte_id", 
                IgoContexte::find(array("order" => "nom")), 
                "using" => array("id", "nom"), 
                "emptyText" => "Choisir...", 
                "useEmpty" => true,
                "class" => "form-control"
            ));
        ?>
    </div>
</div>

<div class="row">
   
    <div class="col-lg-8 col-lg-offset-4 col-md-8 col-md-offset-4 col-sm-8 col-xs-12">
        <?php echo $this->tag->submitButton(array("Générer", "class"=>'btn btn-primary')) ?>
    </div>
</div>

<?php echo $this->tag->hiddenField("id") ?>

</form>
