<?php use Phalcon\Tag; ?>
<?php echo $this->getContent(); ?>
<?php $this->partial("commun/titre", array("titre" =>"Classifications")) ?>
<?php $this->partial("commun/search_entete") ?>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Id</th>
            <th><?php echo $this->tag->linkTo("igo_classification/search?order=nom", "Nom <span class='glyphicon glyphicon-resize-vertical'></span>") ?></th>
            <th><?php echo $this->tag->linkTo("igo_classification/search?order=description", "Description <span class='glyphicon glyphicon-resize-vertical'></span>") ?></th>
            <th>Code GeoNetwork</th>
            <th>Date modifié</th>
         </tr>
    </thead>
    <tbody>
    <?php foreach ($page->items as $igo_classification) { ?>
        <tr>
            <td><?php echo $igo_classification->id ?></td>
            <td><?php echo $igo_classification->nom ?></td>
            <td><?php echo $igo_classification->description ?></td>
            <td><?php echo $igo_classification->code_geonetwork ?></td>
            <td><?php echo $igo_classification->date_modif ?></td>
            <td><?php echo $this->igo_tag->linkIfAdmin(array("igo_classification/edit/" . $igo_classification->id."/".$r_controller."/".$action."/".$parameters, "Editer")); ?></td>
            <td><?php echo $this->igo_tag->linkIfAdmin(array("igo_classification/delete/" . $igo_classification->id."/".$r_controller."/".$action."/".$parameters, "Détruire", 'data-confirmation'=>'supprimer')); ?></td>
        </tr>
    <?php } ?>
    </tbody>
</table>
<?php $this->partial("commun/search_pagination") ?>