<?php use Phalcon\Tag; ?>
<?php echo $this->getContent(); ?>
<?php $this->partial("commun/titre", array("titre" =>"Classifications")) ?>
<?php $this->partial("commun/search_entete") ?>

<table class="table table-striped table-search">
    <thead>
        <tr>
            <th class="id"><?php echo $this->tag->linkTo("igo_classification/search?order=id", "Id<span class='glyphicon glyphicon-resize-vertical'></span>") ?></th>
            <th><?php echo $this->tag->linkTo("igo_classification/search?order=nom", "Nom <span class='glyphicon glyphicon-resize-vertical'></span>") ?></th>
            <th><?php echo $this->tag->linkTo("igo_classification/search?order=description", "Description <span class='glyphicon glyphicon-resize-vertical'></span>") ?></th>
            <th>Code GeoNetwork</th>
            <th class="date_modif"><?php echo $this->tag->linkTo("igo_classification/search?order=date_modif", "Date de modification<span class='glyphicon glyphicon-resize-vertical'></span>") ?></th>
            <th class="actions"></th>
         </tr>
    </thead>
    <tbody>
    <?php foreach ($page->items as $igo_classification) { ?>
        <tr>
            <td><?php echo $igo_classification->id ?></td>
            <td><?php echo $igo_classification->nom ?></td>
            <td><?php echo $igo_classification->description ?></td>
            <td><?php echo $igo_classification->code_geonetwork ?></td>
            <td><?php echo $igo_classification->date_modif ?></td>
            <td class="overflow-visible"> 
                <div class="dropdown">
                    <button class="btn btn-default dropdown-toggle" type="button" id="dropdown-actions" data-toggle="dropdown" aria-expanded="true">
                        Actions
                        <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
                        <li><?php echo $this->igo_tag->linkIfAdmin(array("igo_classification/edit/" . $igo_classification->id."/".$r_controller."/".$action."/".$parameters, "<span class='glyphicon glyphicon-pencil' aria-hidden='true'></span> Modifier")); ?></li>
                        <li><?php echo $this->igo_tag->linkIfAdmin(array("igo_classification/delete/" . $igo_classification->id."/".$r_controller."/".$action."/".$parameters, "<span class='glyphicon glyphicon-trash' aria-hidden='true'></span> Détruire", 'data-confirmation'=>'supprimer')); ?></li>
                    </ul>
                </div>
            </td>
        </tr>
    <?php } ?>
    </tbody>
</table>
<?php $this->partial("commun/search_pagination") ?>