<?php use Phalcon\Tag; ?>
<?php echo $this->getContent(); ?>
<?php $this->partial("commun/titre", array("titre" =>"Géométries")) ?>
<?php $this->partial("commun/search_entete") ?>

<table class="table table-striped table-search">
    <thead>
        <tr>
            <th class="id"><?php echo $this->tag->linkTo("igo_geometrie/search?order=id", "Id<span class='glyphicon glyphicon-resize-vertical'></span>") ?></th>
            <th>Classe d'entité</th>
            <th>Type de géométrie</th>
            <th>Date de chargement</th>
            <th>Remarque</th>
            <th class="date_modif"><?php echo $this->tag->linkTo("igo_geometrie/search?order=date_modif", "Date de modification <span class='glyphicon glyphicon-resize-vertical'></span>") ?></th>
            <th class="actions"></th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($page->items as $igo_geometrie) { ?>
        <tr>
            <td><?php echo $igo_geometrie->id ?></td>
            <td><?php if ($igo_geometrie->IgoClasseEntite) { echo $igo_geometrie->IgoClasseEntite->nom;} ?></td>
            <td><?php if ($igo_geometrie->IgoGeometrieType) { echo $igo_geometrie->IgoGeometrieType->nom;} ?></td>
            <td><?php echo $igo_geometrie->date_chargement ?></td>
            <td><?php echo $igo_geometrie->remarque ?></td>
            <td><?php echo $igo_geometrie->date_modif ?></td>
            <td class="overflow-visible"> 
                <div class="dropdown">
                    <button class="btn btn-default dropdown-toggle" type="button" id="dropdown-actions" data-toggle="dropdown" aria-expanded="true">
                        Actions
                        <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
                        <li><?php echo $this->igo_tag->linkIfAdmin(array("igo_geometrie/edit/" . $igo_geometrie->id."/".$r_controller."/".$action."/".$parameters, "<span class='glyphicon glyphicon-pencil' aria-hidden='true'></span> Modifier")); ?></li>
                        <li><?php echo $this->igo_tag->linkIfAdmin(array("igo_geometrie/delete/". $igo_geometrie->id."/".$r_controller."/".$action."/".$parameters, "<span class='glyphicon glyphicon-trash' aria-hidden='true'></span> Détruire", 'data-confirmation'=>'supprimer')); ?></li>
                        <li><?php echo $this->tag->linkTo(array("geometrie_et_attribut/do/" . $igo_geometrie->id, "<span class='glyphicon' aria-hidden='true'></span> Voir les attributs", "target"=>"_parent")); ?></li>
                        <li><?php echo $this->tag->linkTo(array("geometrie_et_couche/do/" . $igo_geometrie->id, "<span class='glyphicon' aria-hidden='true'></span> Voir ses couches", "target"=>"_parent")); ?></li>
                    </ul>
                </div>
            </td>
        </tr>
    <?php } ?>
    </tbody>
</table>
<?php $this->partial("commun/search_pagination") ?>