<?php echo \Phalcon\Tag::javascriptInclude("js/jquery/suivi-lien.js"); ?>
<script>
$(document).ready(function(){
    $('#editer-classe_entite_id').suiviLien({idInput:'classe_entite_id'});
    $('#editer-connexion_id').suiviLien({idInput:'connexion_id'});
});
</script>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="classe_entite_id">Nom de la classe entité<span class="glyphicon glyphicon-asterisk oblig"></span></label>
    </div>
    <div class="col-lg-4 col-md-8 col-sm-8 col-xs-12">  
        <?php
        echo $this->tag->select(array(
            "classe_entite_id",
            IgoClasseEntite::find(array("order" => "nom")), "using" => array("id", "nom"),
            "emptyText" => "Choisir...",
            "useEmpty" => true,
            "class" => "form-control"));
        ?>
        
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="geometrie_type_id">Type de géométrie<span class="glyphicon glyphicon-asterisk oblig"></span></label>
    </div>
    <div class="col-lg-4 col-md-8 col-sm-8 col-xs-12">
        <?php
        echo $this->tag->select(array(
            "geometrie_type_id",
            IgoGeometrieType::find(array("order" => "nom")),
            "using" => array("id", "nom"),
            "emptyText" => "Choisir...",
            "useEmpty" => true,
            "class" => "form-control"));
        ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="type">Point d'accès<span class="glyphicon glyphicon-asterisk oblig"></span></label>
    </div>
    <div class="col-lg-2 col-md-8 col-sm-8 col-xs-12">
        <?php
        echo $this->tag->select(array(
            "acces",
            ($this->view->getActionName() == "index") ?
                    array(
                "D" => "Distant",
                "L" => "Local") :
                    array(
                "D" => "Distant",
                "L" => "Local"),
            "class" => "form-control"));
        ?>
    </div>
</div>
<div class="row" data-acces-type="L">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="vue_defaut">Vue</label>
    </div>
    <div class="col-lg-4 col-md-8 col-sm-8 col-xs-12">
        <?php echo $this->tag->textField(array(
                "vue_defaut",
                "class" => "form-control")); ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="ind_inclusion">Inclusion des attributs<span class="glyphicon glyphicon-asterisk oblig"></span></label>
    </div>
    <div class="col-lg-4 col-md-8 col-sm-8 col-xs-12">
        <?php
        echo $this->tag->select(array(
            "ind_inclusion",
            ($this->view->getActionName() == "index") ?
                    array(
                "" => " ",
                "T" => "Tous",
                "E" => "Liste d'exclusion",
                "I" => "Liste d'inclusion") :
                    array(
                "T" => "Tous",
                "E" => "Liste d'exclusion",
                "I" => "Liste d'inclusion"),
            "class" => "form-control"));
        ?>

    </div>
</div>
<div class="row" data-acces-type="L">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="date_chargement">Date de chargement</label>
    </div>
    <div class="col-lg-3 col-md-8 col-sm-8 col-xs-12">
        <div class='input-group date' id='date_chargement'  name='date_chargement' data-date-format="YYYY-MM-DD HH:MM:SS" >
            <?php echo $this->tag->textField(array("date_chargement",  "class" => "form-control")) ?> <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
        </div>
        <script>
                $(function() {
                    $('#date_chargement').datetimepicker({
                        defaultDate: "<?php echo ($this->tag->getValue("date_chargement") <> "") ? $this->tag->getValue("date_chargement") : date("Y-m-d h:m:s"); ?>",
                        pick12HourFormat: false
                    });
                });

        </script>           
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="connexion_id">Connexion<span class="oblig">*</span></label>
    </div>
    <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12">
        <?php
        echo $this->tag->select(array(
            "connexion_id",
            IgoConnexion::find(array("order" => "nom")),
            "using" => array("id", "nom"),
            "emptyText" => "Choisir...",
            "useEmpty" => true,
            "class" => "form-control"))
        ?>
    </div>
    <div class="col-lg-1 col-md-1 col-sm-1 col-xs-1">
      <?php echo $this->igo_tag->linkIfAdmin(array("igo_connexion/new" . "/" . $r_controller . "/" . $action . "/" . $parameters, "Créer")); ?>
    </div>
    <div class="col-lg-1 col-md-1 col-sm-1 col-xs-1">
      <?php echo $this->igo_tag->linkIfAdmin(array(
                    '', 
                    "<span class='glyphicon glyphicon-pencil' aria-hidden='true'></span> Modifier",
                    'id'=>'editer-connexion_id',
                    'data-suivilien-href' => $this->config->uri->pilotage."/igo_connexion/edit" . "/{valeur}/" . $r_controller . "/" . $action . "/" . $parameters,
                    'target' => '_blank'
              )); ?>
    </div>

</div>
<div class="row" data-acces-type="L">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="mf_layer_data">Chemin d'accès des données</label>
    </div>
    <div class="col-lg-6 col-md-8 col-sm-8 col-xs-12">
        <?php echo $this->tag->textField(array(
                "mf_layer_data",
                "class" => "form-control"
            )); ?>
    </div>
</div>
<div class="row" data-acces-type="L">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="echelle_prod">Échelle de production</label>
    </div>
    <div class="col-lg-4 col-md-6 col-sm-6 col-xs-12">
        <?php echo $this->tag->textField(array(
                "echelle_prod",
                "class" => "form-control"
            )); ?>
    </div>
</div>
<div class="row" data-acces-type="L">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="mf_layer_projection">Projection<span class="glyphicon glyphicon-asterisk oblig"></span></label>
    </div>
    <div class="col-lg-2 col-md-2 col-sm-2 col-xs-12">
        <?php echo $this->tag->textField(array(
                "mf_layer_projection", 
                "class" => "form-control"
            )); ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="remarque">Remarque</label>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
        <?php echo $this->tag->textField(array("remarque", 
                "class" => "form-control"
            )); ?>
    </div>
</div>
<?php $this->partial("commun/date_modification"); ?>