<?php use Phalcon\Tag; ?>
<?php $this->partial("commun/titre", array("titre" =>"Associer des couches")) ?>
<?php echo $this->getContent(); ?>
<?php echo $this->tag->form() ?>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Id Assoc.</th>
            <th>Type</th>
            <th>Description</th>
            <th>Ind. fond de carte</th>
            <th>Fond de carte</th>
            <th>Visible</th>
            <th>Active</th>
            <th>mf layer meta name</th>
            <th>mf layer meta title</th>
            <th>mf layer meta group title</th>
         </tr>
    </thead>
    <tbody>
    <?php foreach ($page->items as $row) {  ?>
        <tr>
            <td><?php echo $row->id ?></td>
            <td><?php echo $row->type ?></td>
            <td><?php echo $row->description ?></td>
            <td><?php echo $this->tag->textField(array("ind_fond_de_carte_".$row->couche_id."_".$row->id,"value" => $row->ind_fond_de_carte, "size" => 1)) ?></td>
            <td><?php echo $this->tag->checkField(array("est_fond_de_carte_".$row->couche_id."_".$row->id, "value" => 1,"disabled" =>1, $row->est_fond_de_carte?"checked":"unchecked" => 1)) ?></td>
            <td><?php echo $this->tag->checkField(array("est_visible_".$row->couche_id."_".$row->id, "value" => 1, $row->est_visible?"checked":"unchecked" => 1)) ?></td>
            <td><?php echo $this->tag->checkField(array("est_active_".$row->couche_id."_".$row->id, "value" => 1, $row->est_active?"checked":"unchecked" => 1)) ?></td>
            <td><?php echo $this->tag->textField(array("mf_layer_meta_name_".$row->couche_id."_".$row->id,"value" => $row->mf_layer_meta_name,"value" => $row->mf_layer_meta_name,"size" => 10)) ?></td>
            <td><?php echo $this->tag->textField(array("mf_layer_meta_title_".$row->couche_id."_".$row->id,"value" => $row->mf_layer_meta_title, "size" => 10)) ?></td>
            <td><?php echo $this->tag->textField(array("mf_layer_meta_group_title_".$row->couche_id."_".$row->id,"value" => $row->mf_layer_meta_group_title, "size" => 10)) ?></td>
            <td><?php echo $this->tag->linkTo(array("igo_couche_contexte/edit/" . $row->id."/".$controller."/".$action."/".$parameters, "<span class='glyphicon glyphicon-pencil' aria-hidden='true'></span> Modifier")) ?></td>
        </tr>

    <?php } ?>  
        <tr>
            <td><?php echo $this->tag->submitButton("Sauver") ?></td>
        </tr>
    </tbody>
     <?php if ($page->total_pages>1) { ?>
    <tbody>
        <tr>
            <td colspan="2" align="right">
                <table align="center">
                    <tr>
                        <td><?php echo $this->tag->linkTo("igo_couche/associerContexte/".$contexte_id, "Premier") ?></td>
                        <td><?php echo $this->tag->linkTo("igo_couche/associerContexte/".$contexte_id."/".$page->before, "Précédent") ?></td>
                        <td><?php echo $this->tag->linkTo("igo_couche/associerContexte/".$contexte_id."/".$page->next, "Suivant") ?></td>
                        <td><?php echo $this->tag->linkTo("igo_couche/associerContexte/".$contexte_id."/".$page->last, "Dernier") ?></td>
                        <td><?php echo $page->current, "/", $page->total_pages ?></td>
                    </tr>
                </table>
            </td>
        </tr>
    <tbody>
    <?php } ?>
</table>
