<?php use Phalcon\Tag; ?>

<?php echo $this->getContent(); ?>
    
<?php echo $this->tag->form() ?>

<?php $this->partial("commun/titre", array("titre" =>"Associer des couches")) ?>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Id</th>
            <th>Type</th>
            <th>Description</th>
            <th>Lecture</th>
            <th>Analyse</th>
            <th>Analyse(Sortie)</th>
            <th>Écriture</th>
            <th>Exportation</th>
         </tr>
    </thead>
    <tbody>
    <?php foreach ($page->items as $row) {  ?>
        <tr>
            <td><?php echo $row->id ?></td>
            <td><?php echo $row->type ?></td>
            <td><?php echo $row->description ?></td>
            <td><?php echo $this->tag->checkField(array("est_lecture_".$row->id, "value" => 1, $row->est_lecture?"checked":"unchecked" => 1)) ?></td>
            <td><?php echo $this->tag->checkField(array("est_analyse_".$row->id, "value" => 1, $row->est_analyse?"checked":"unchecked" => 1)) ?></td>
            <td><?php echo $this->tag->checkField(array("est_analyse_out_".$row->id, "value" => 1, $row->est_analyse_out?"checked":"unchecked" => 1)) ?></td>
            <td><?php echo $this->tag->checkField(array("est_ecriture_".$row->id, "value" => 1, $row->est_ecriture?"checked":"unchecked" => 1)) ?></td>
            <td><?php echo $this->tag->checkField(array("est_exportation_".$row->id, "value" => 1, $row->est_exportation?"checked":"unchecked" => 1)) ?></td>
            <td><?php echo $this->tag->linkTo(array("igo_permission/edit/" . $row->id."/".$controller."/".$action."/".$parameters, "Editer")) ?></td>
        </tr>

    <?php } ?>  
        <tr>
            <td><?php echo $this->tag->submitButton("Sauver") ?></td>
        </tr>
    </tbody>
     <?php if ($page->total_pages>1) { ?>
    <tbody>
        <tr>
            <td colspan="2" align="right">
                <table align="center">
                    <tr>
                        <td><?php echo $this->tag->linkTo("igo_couche/search", "Premier") ?></td>
                        <td><?php echo $this->tag->linkTo("igo_couche/search?page=" . $page->before, "Précédent") ?></td>
                        <td><?php echo $this->tag->linkTo("igo_couche/search?page=" . $page->next, "Suivant") ?></td>
                        <td><?php echo $this->tag->linkTo("igo_couche/search?page=" . $page->last, "Dernier") ?></td>
                        <td><?php echo $page->current, "/", $page->total_pages ?></td>
                    </tr>
                </table>
            </td>
        </tr>
    <tbody>
    <?php } ?>
</table>
