<?php echo $this->getContent(); ?>
<table width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array($retour, "<button type='button' class='btn btn-default'><span class='glyphicon glyphicon-share-alt glyphicon-retour'></span>Retour</button>")); ?></td>
    <tr>
</table>
<?php echo $this->tag->stylesheetLink("csw/fiche.css");?>
<div class="wrapper">
<div class="acc_colonne1" id="contenu">
<?php echo $fiche;?>
</div>
</div>
