<?php echo \Phalcon\Tag::javascriptInclude("js/jquery/suivi-lien.js"); ?>
<script>
$(document).ready(function(){
    $('#editer-geometrie_id').suiviLien({idInput:'geometrie_id'});
    $('*[data-toggle="tooltip"]').tooltip({html: true});
});
</script>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="mf_layer_meta_title">Titre de la couche<span class="glyphicon glyphicon-asterisk oblig"></span></label>
    </div>
    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
        <?php echo $this->tag->textField(array(
                "mf_layer_meta_title", 
                "class" => "form-control"
            ));
        ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="mf_layer_name">Nom de code<span class="glyphicon glyphicon-asterisk oblig"></span></label>
    </div>
    <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
        <?php echo $this->tag->textField(array("mf_layer_name", 
            "class" => "form-control"
            ));
        ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="description">Description</label>
    </div>
    <div class="col-lg-6 col-md-8 col-sm-8 col-xs-12">
        <?php echo $this->tag->textField(array(
                "description", 
                "class" => "form-control"
            ));
        ?>
    </div>
</div>
<?php if("index" != $action):?>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="fiche_csw_id">Id de fiche de métadonnées (catalogue CSW)</label>
    </div>
    <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
        <?php echo $this->tag->textField(array(
                "fiche_csw_id", 
                "class" => "form-control"
            ));
        ?>
    </div>
    <div class="col-lg-1 col-md-1 col-sm-1 col-xs-12">
        <?php 

            echo $this->tag->linkTo(array("igo_couche/fiche" . "/" . $this->tag->getValue("id") . "/" . 
                                    $r_controller . "/" . $action . "/" . $parameters, 
                                    "Consulter"));
       
        ?>
    </div>
</div>
<?php endif;?>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="mf_layer_meta_group_title">Titre du groupe dans l'arborescence</label>
    </div>
    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
        <?php echo $this->tag->textField(array(
                "mf_layer_meta_group_title", 
                "class" => "form-control"
            ));
        ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="mf_layer_group">Code de groupe</label>
    </div>
    <div class="col-lg-6 col-md-8 col-sm-8 col-xs-12">
        <?php echo $this->tag->textField(array(
                "mf_layer_group", 
                "class" => "form-control",
                "data-toggle" => "tooltip",
                "data-placement" => "right",
                "title" => "Paramètre <b>Group</b> du mapfile"
            ));
        ?>
    </div>
</div>
<?php if("index" != $action):?>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="geometrie_id">Géometrie<span class="glyphicon glyphicon-asterisk oblig"></span></label>
    </div>
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
        <?php echo $this->tag->select(array(
                "geometrie_id", 
                $geometrie_desc, 
                "using" => array("id", "nom"), 
                "emptyText" => "Choisir...", 
                "useEmpty" => true,
                "class" => "form-control"
            ));
        ?>
    </div>
    <!--
    <div class="col-lg-1 col-md-1 col-sm-1 col-xs-12">
          <?php echo $this->tag->linkTo(array(
                    "igo_geometrie/new" . "/" . $r_controller . "/" . $action . "/" . $parameters, 
                    "Créer", 
                    'class'=>'creer', 
                    'id'=>'creer-geometrie_id')); ?>
    </div>
    <div class="col-lg-1 col-md-1 col-sm-1 col-xs-12">
          <?php echo $this->tag->linkTo(array(
                    "", 
                    "Éditer", 
                    'class'=>'editer', 
                    'id'=>'editer-geometrie_id',
                    'data-suivilien-href' =>$this->config->uri->pilotage."/igo_geometrie/edit" . "/{valeur}/" . $r_controller . "/" . $action . "/" . $parameters,
                    'target'=>'_blank'
                )); ?>
    </div>
    -->
</div>
<?php endif;?>
<?php if("index" != $action):?>
<div class="row">
    <div class="col-lg-8 col-lg-offset-2">
        <hr>    
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="layer_a_order">Ordre A</label>
    </div>
    <div class="col-lg-2 col-md-3 col-sm-3 col-xs-12">
        <?php echo $this->tag->textField(array(
                "layer_a_order", 
                "class" => "form-control"
            ));
        ?>
    </div>
</div>
<?php endif;?>
<?php if("index" != $action):?>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="mf_layer_meta_z_order">Ordre Z</label>
        <label for="mf_layer_meta_z_order">Ordre (affichage ou bien arbo???)</label>
        <label for="mf_layer_meta_z_order">Ordre Z</label>
    </div>
    <div class="col-lg-2 col-md-3 col-sm-3 col-xs-12">
        <?php echo $this->tag->textField(array(
                "mf_layer_meta_z_order", 
                "class" => "form-control"
            ));
        ?>
    </div>
</div>
<?php endif;?>
<?php if("index" != $action):?>
<div class="row" data-acces-type="L">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="mf_layer_minscale_denom">Échelle minimale d'affichage</label>
    </div>
    <div class="col-lg-2 col-md-2 col-sm-2 col-xs-12">
        <?php echo $this->tag->textField(array(
                "mf_layer_minscale_denom", 
                "type" => "number", 
                "class" => "form-control"
            ));
        ?>
    </div>
</div>
<?php endif;?>
<?php if("index" != $action):?>
<div class="row" data-acces-type="L">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="mf_layer_maxscale_denom">Échelle maximale d'affichage</label>
    </div>
    <div class="col-lg-2 col-md-3 col-sm-4 col-xs-12">
        <?php echo $this->tag->textField(array(
                "mf_layer_maxscale_denom", 
                "type" => "number", 
                "class" => "form-control"
            ));
        ?>
    </div>
</div>
<?php endif;?>
<?php if("index" != $action):?>
<div class="row" data-acces-type="L">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="mf_layer_labelminscale_denom">Échelle minimale d'affichage des étiquettes</label>
    </div>
    <div class="col-lg-2 col-md-3 col-sm-3 col-xs-12">
        <?php echo $this->tag->textField(array(
                "mf_layer_labelminscale_denom", 
                "type" => "number", 
                "class" => "form-control"
            ));
        ?>
    </div>
</div>
<?php endif;?>
<?php if("index" != $action):?>
<div class="row" data-acces-type="L">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="mf_layer_labelmaxscale_denom">Échelle maximale d'affichage des étiquettes</label>
    </div>
    <div class="col-lg-2 col-md-3 col-sm-3 col-xs-12">
        <?php echo $this->tag->textField(array(
                "mf_layer_labelmaxscale_denom", 
                "type" => "number", 
                "class" => "form-control"
            ));
        ?>
    </div>
</div>
<?php endif;?>
<?php if("index" != $action):?>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="max_zoom_level">Niveau de zoom maximum</label>
    </div>
    <div class="col-lg-2 col-md-3 col-sm-3 col-xs-12">
        <?php 
        $zoomLevel = array(0=>0, 1=>1, 2=>2, 3=>3, 4=>4, 5=>5,
                            6=>6, 7=>7, 8=>8, 9=>9, 10=>10, 11=>11,
                            12=>12, 13=>13, 14=>14, 15=>15, 16=>16, 
                            17=>17, 18=>18, 19=>19, 20=>20);
        
        echo $this->tag->select(array(
                "max_zoom_level", 
                $zoomLevel, 
                "emptyText" => "Choisir...", 
                "useEmpty" => true,
                "class" => "form-control"
            ));
        ?>
    </div>
</div>
<?php endif;?>
<?php if("index" != $action):?>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="min_zoom_level">Niveau de zoom minimum</label>
    </div>
    <div class="col-lg-2 col-md-3 col-sm-3 col-xs-12">
        <?php  echo $this->tag->select(array(
                "min_zoom_level", 
                $zoomLevel, 
                "emptyText" => "Choisir...", 
                "useEmpty" => true,
                "class" => "form-control"
            ));
        ?>
    </div>
</div>
<?php endif;?>
<?php if("index" != $action):?>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="mf_layer_opacity">Opacité</label>
    </div>
    <div class="col-lg-2 col-md-3 col-sm-3 col-xs-12">
        <?php echo $this->tag->textField(array(
                "mf_layer_opacity", 
                "type" => "number", 
                "class" => "form-control"
            ));
        ?>
    </div>
</div>
<?php endif;?>
<?php if("index" != $action):?>
<div class="row">
    <div class="col-lg-8 col-lg-offset-2">
        <hr>    
    </div>
</div>
<div class="row">
    <div  class="testgris col-lg-10 col-lg-offset-1 col-md-10 col-md-offset-1 col-sm-12 col-xs-12">&nbsp</div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="est_commune" class="pas-important">Commune</label>
    </div>
    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
        <?php echo $this->tag->checkField(array("est_commune", "value" => 1)) ?>
    </div>
</div>
<?php endif;?>
<?php if("index" != $action):?>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="est_publique" class="pas-important">Publique</label>
    </div>
    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
        <?php echo $this->tag->checkField(array("est_publique", "value" => 1)) ?>
    </div>
</div>
<?php endif;?>
<?php if("index" != $action):?>

<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="mf_layer_meta_name" class="pas-important">Mf Layer Meta Name (est habituellement le même que nom de code)</label>
    </div>
    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
        <?php echo $this->tag->textField(array(
                "mf_layer_meta_name", 
                "class" => "form-control"
            ));
        ?>
    </div>
</div>
<?php endif;?>
<?php if("index" != $action):?>
<div class="row" data-acces-type="L">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="mf_layer_filtre" class="pas-important">Condition d'affichage</label>
    </div>
    <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
        <?php echo $this->tag->textField(array(
                "mf_layer_filtre", 
                "class" => "form-control"
            ));
        ?>
    </div>
</div>
<?php endif;?>
<?php if("index" != $action):?>
<div class="row" data-acces-type="L">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="service_tuile" class="pas-important">Nom de l'attribut d'affichage des étiquettes</label>
    </div>
    <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
        <?php echo $this->tag->textField(array(
                "mf_layer_labelitem", 
                "class" => "form-control"
            ));
        ?>
    </div>
</div>
<?php endif;?>
<?php if("index" != $action):?>
<div class="row" data-acces-type="L">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="mf_layer_meta_def" class="pas-important">Mf Of Layer Of Meta Of Def</label>
    </div>
    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
        <?php echo $this->tag->textArea(array(
                'mf_layer_meta_def', 
                'cols' => 50, 
                'rows' => 5,
                "class" => "form-control"
            )); 
        ?>
    </div>
</div>
<?php endif;?>
<?php if("index" != $action):?>
<div class="row" data-acces-type="L">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="mf_layer_def" class="pas-important">Mf Of Layer Of Def</label>
    </div>
    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
        <?php echo $this->tag->textArea(array(
                'mf_layer_def', 
                'cols' => 50, 
                'rows' => 10,
                "class" => "form-control"
            ));
        ?>
    </div>
</div>
<?php endif;?>
<?php if("index" != $action):?>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="service_tuile" class="pas-important">Service de tuile</label>
    </div>
    <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
        <?php echo $this->tag->textField(array(
                "service_tuile", 
                "class" => "form-control"
            ));
        ?>
    </div>
</div>
<?php endif;?>
<?php if("index" != $action):?>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="mf_layer_meta_wfs_max_feature" class="pas-important">Nombre maximale d'éléments WFS</label>
    </div>
    <div class="col-lg-2 col-md-3 col-sm-3 col-xs-12">
        <?php echo $this->tag->textField(array(
                "mf_layer_meta_wfs_max_feature", 
                "type" => "number", 
                "class" => "form-control"
            ));
        ?>
    </div>
</div>
<?php endif;?>
<?php if("index" != $action):?>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="est_fond_de_carte" class="pas-important">Fond de carte</label>
    </div>
    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
        <?php echo $this->tag->checkField(array("est_fond_de_carte", "value" => 1)) ?>

    </div>
</div>
<?php endif;?>
<?php if("index" != $action):?>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="mf_layer_meta_attribution_title" class="pas-important">Attribution</label>
    </div>
    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
         <?php echo $this->tag->textArea(array(
                'mf_layer_meta_attribution_title', 
                'cols' => 50, 
                'rows' => 5,
                "class" => "form-control"
            )); 
        ?>
    </div>
</div>
<?php endif;?>
<?php $this->partial("commun/date_modification"); ?>
<?php echo $this->tag->hiddenField(array('acces')) ?>