<?php use Phalcon\Tag; ?>
<?php echo $this->getContent(); ?>
<?php $this->partial("commun/titre", array("titre" =>"Association groupes et couches")) ?>
<?php $this->partial("commun/search_entete") ?>

<table class="table table-striped table-search">
    <thead>
        <tr>
            <th class="id"><?php echo $this->tag->linkTo("igo_groupe_couche/search?order=id", "Id<span class='glyphicon glyphicon-resize-vertical'></span>") ?></th>
            <th><?php echo $this->tag->linkTo("igo_groupe_couche/search?order=couche_id", "Couche <span class='glyphicon glyphicon-resize-vertical'></span>") ?></th>
            <th><?php echo $this->tag->linkTo("igo_groupe_couche/search?order=groupe_id", "Groupe <span class='glyphicon glyphicon-resize-vertical'></span>") ?></th>
               <th class="editer"></th>
            <th class="detruire"></th> 
        </tr>
    </thead>
    <tbody>
    <?php foreach ($page->items as $igo_groupe_couche) { ?>
        <tr>
            <td><?php echo $igo_groupe_couche->id ?></td>
            
            <td><?php  if ($igo_groupe_couche->IgoCouche){echo $igo_groupe_couche->IgoCouche->mf_layer_meta_title;} ?></td>
            <td><?php  if ($igo_groupe_couche->IgoGroupe){echo $igo_groupe_couche->IgoGroupe->nom;} ?></td>
  
            <td><?php echo $this->igo_tag->linkIfAdmin(array("igo_groupe_couche/edit/" . $igo_groupe_couche->id."/".$r_controller."/".$action."/".$parameters, "<span class='glyphicon glyphicon-pencil' aria-hidden='true'></span> Modifier")); ?></td>
            <td><?php echo $this->igo_tag->linkIfAdmin(array("igo_groupe_couche/delete/" . $igo_groupe_couche->id."/".$r_controller."/".$action."/".$parameters, "<span class='glyphicon glyphicon-trash' aria-hidden='true'></span> Détruire", 'data-confirmation'=>'supprimer')); ?></td>
            <td><?php echo $this->tag->linkTo(array($this->config->uri->navigateur .'groupe/' . $igo_groupe_couche->id, "", "class" =>"glyphicon glyphicon-eye-open", "target"=>"_blank", 'local' =>FALSE)); ?></td>
        </tr>
    <?php } ?>
    </tbody>
</table>
<?php $this->partial("commun/search_pagination") ?>