
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="nom">Nom<span class="glyphicon glyphicon-asterisk oblig"></span></label>
    </div>
    <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
        <?php
        echo $this->tag->select(array(
            "groupe_id",
            IgoGroupe::find(array("order" => "nom")),
            "using" => array("id", "nom"),
            "emptyText" => "Choisir...",
            "useEmpty" => true, 
            "class" => "form-control"
        ));
        ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="groupe_id">Couche<span class="glyphicon glyphicon-asterisk oblig"></span></label>
    </div>
    <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
        <?php
        echo $this->tag->select(array(
            "couche_id",
            IgoCouche::find(array("order" => "mf_layer_meta_title")),
            "using" => array("id", "mf_layer_meta_title"),
            "emptyText" => "Choisir...",
            "useEmpty" => true, 
            "class" => "form-control"
        ));
        ?>
    </div>
</div>
<?php $this->partial("commun/date_modification"); ?>