<?php use Phalcon\Tag; ?>
<?php echo $this->getContent(); ?>
<?php $this->partial("commun/titre", array("titre" =>"Classes entité")) ?>
<?php $this->partial("commun/search_entete") ?>
<table class="table table-striped table-search table-search-igo_classe_entite">
    <thead>
        <tr>
            <th class='id'><?php echo $this->tag->linkTo("igo_classe_entite/search?order=id", "Id<span class='glyphicon glyphicon-resize-vertical'></span>") ?></th>
            <th><?php echo $this->tag->linkTo("igo_classe_entite/search?order=nom", "Nom <span class='glyphicon glyphicon-resize-vertical'></span>") ?></th>
            <th><?php echo $this->tag->linkTo("igo_classe_entite/search?order=description", "Description <span class='glyphicon glyphicon-resize-vertical'></span>") ?></th>
            <th>Classification</th>
            <th>Organisme responsable</th>
            <th>Contact</th>
            <th class='catalogue-csw'>Catalogue CSW</th>
            <th><?php echo $this->tag->linkTo("igo_classe_entite/search?order=date_modif", "Date de modification <span class='glyphicon glyphicon-resize-vertical'></span>") ?></th>
            <th class="editer"></th>
            <th class="detruire"></th>
            <th class="geometries"></th>
        </tr>
    </thead>
    <tbody>
            <?php foreach ($page->items as $igo_classe_entite) { ?>
            <tr>
                <td><?php echo $igo_classe_entite->id ?></td>
                <td><?php echo $igo_classe_entite->nom ?></td>
                <td><?php echo $igo_classe_entite->description ?></td>
                <td><?php if ($igo_classe_entite->IgoClassification) {
                        echo $igo_classe_entite->IgoClassification->nom;
                    } ?>
                </td>
                <td><?php if ($igo_classe_entite->IgoOrganismeResponsable) {
                        echo $igo_classe_entite->IgoOrganismeResponsable->nom;
                    } ?>
                </td>
                <td><?php if ($igo_classe_entite->IgoContact) {
                            echo $igo_classe_entite->IgoContact->nom . ", " . $igo_classe_entite->IgoContact->prenom;
                    } ?>
                </td>
                <?php if ($igo_classe_entite->IgoCatalogueCsw) { ?>
                <td title="<?php echo $igo_classe_entite->IgoCatalogueCsw->url; ?>"> <?php echo $igo_classe_entite->IgoCatalogueCsw->url; ?>
                    <?php } else { ?>
                 <td></td>
                <?php } ?>
                <td><?php echo $igo_classe_entite->date_modif ?></td>
                <td class="editer"><?php echo $this->igo_tag->linkIfAdmin(array("igo_classe_entite/edit/" . $igo_classe_entite->id . "/" . $r_controller . "/" . $action . "/" . $parameters, "Editer")); ?></td>
                <td class="detruire"><?php echo $this->igo_tag->linkIfAdmin(array("igo_classe_entite/delete/" . $igo_classe_entite->id . "/" . $r_controller . "/" . $action . "/" . $parameters, "Détruire", 'data-confirmation'=>'supprimer')); ?></td>
                <td class="geometries"><?php echo $this->tag->linkTo(array("classe_entite_et_geometrie/do/" . $igo_classe_entite->id, "Géométries")); ?></td>
            </tr>
            <?php } ?>
    </tbody>
</table>
<?php $this->partial("commun/search_pagination") ?>