<?php

use Phalcon\Db\RawValue;
?>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="nom">Nom<span class="glyphicon glyphicon-asterisk oblig"></span></label>
    </div>
    <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
        <?php echo $this->tag->textField(array(
                "nom", 
                "class" => "form-control"
            )); 
        ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="description">Description</label>
    </div>
    <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
        <?php echo $this->tag->textField(array(
                "description", 
                "class" => "form-control"
            )); 
        ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="source_entite_id">Source d'entités</label>
    </div>
    <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
        <?php echo $this->tag->select(array(
                "source_entite_id", 
                IgoSourceEntite::find(array("order" => "url")), 
                "using" => array("id", "url"), 
                "emptyText" => "Choisir...", 
                "useEmpty" => true, 
                "class" => "form-control"
            )); 
        ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="classification_id">Classification<span class="glyphicon glyphicon-asterisk oblig"></span></label>
    </div>
    <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
        <?php echo $this->tag->select(array(
                "classification_id", 
                IgoClassification::find(array("order" => "nom")), 
                "using" => array("id", "nom"), 
                "emptyText" => "Choisir...", 
                "useEmpty" => true, 
                "class" => "form-control"
            )); 
        ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="organisme_responsable_id">Organisme responsable<span class="glyphicon glyphicon-asterisk oblig"></span></label>
    </div>
    <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
        <?php echo $this->tag->select(array(
                "organisme_responsable_id", 
                $organisme_desc, 
                "using" => array("id", "nom"), 
                "emptyText" => "Choisir...", 
                "useEmpty" => true, 
                "class" => "form-control"
            )); 
                ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="contact_id">Contact</label>
    </div>
    <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12"> 
        <?php
        echo $this->tag->select(array(
            "contact_id",
            IgoContact::find(array(
                'columns' => 'id, ' . new RawValue('CONCAT (nom, ", ", prenom) as nomPrenom'),
                "order" => "nom")),
            "using" => array("id", "nomPrenom"),
            "useEmpty" => true,
            'emptyText' => 'Choisir...', 
            "class" => "form-control"
            ));
        ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="remarque">Remarque</label>
    </div>
    <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
        <?php echo $this->tag->textField(array(
                "remarque", 
                "class" => "form-control"
            )); 
        ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="catalogue_csw_id">Catalogue CSW</label>
    </div>
    <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
        <?php
        echo $this->tag->select(array(
            "catalogue_csw_id",
            IgoCatalogueCsw::find(array("order" => "url")),
            "using" => array("id", "url"),
            "emptyText" => "Choisir...",
            "useEmpty" => true, 
            "class" => "form-control"
            ));
        ?>
    </div>
</div>
<?php $this->partial("commun/date_modification"); ?>