<?php use Phalcon\Tag; ?>
<?php echo $this->getContent(); ?>
<?php $this->partial("commun/titre", array("titre" =>"Lister une couche")) ?>
<?php $this->partial("commun/search_entete") ?>

<style>
    .onlineressource{
        overflow:hidden; 
        white-space:nowrap; 
        text-overflow:ellipsis; 
        width:130px; 
        max-width:100px;
    }

</style>
<table class="table table-striped table-search">
    <thead>
        <tr>
            <th>Titre</th>
            <th>Nom</th>
            <th>Filtre</th>
            <th>Publique?</th>
            <th>Connexion</th>
            <th>Géometrie</th>

 
            <th class="editer"></th>
            <th class="detruire"></th>        </tr>
    </thead>
    <tbody>
    <?php foreach ($page->items as $igo_vue_couche) { ?>         
        <tr>
             <td><?php echo $igo_vue_couche->mf_layer_meta_title ?></td>
            <td><?php echo $igo_vue_couche->mf_layer_name ?></td>
            <td><?php echo $igo_vue_couche->mf_layer_filtre ?></td>
            <td><?php echo $igo_vue_couche->est_publique ?></td>
            <td><?php echo $igo_vue_couche->nom_connexion ?></td>
            <td><?php echo $igo_vue_couche->nom_geometrie_type ?></td>

                 <td><?php echo $this->tag->linkTo(array("igo_couche/edit/" . $igo_vue_couche->id . "/" . $r_controller . "/" . $action . "/" . $parameters, "<span class='glyphicon glyphicon-pencil' aria-hidden='true'></span> Modifier")); ?></td>
            <td><?php echo $this->tag->linkTo(array("igo_couche/delete/" . $igo_vue_couche->id . "/" . $r_controller . "/" . $action . "/" . $parameters, "<span class='glyphicon glyphicon-trash' aria-hidden='true'></span> Détruire")); ?></td>
   
        </tr>
    <?php } ?>
    </tbody>
    
<?php $this->partial("commun/search_pagination") ?>





