    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
            <label for="id">Id</label>
        </div>
        <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
            <?php echo $this->tag->textField(array("id", "type" => "number")) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
            <label for="description">Description</label>
        </div>
        <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
            <?php echo $this->tag->textField(array("description", "size" => 30)) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
            <label for="geometrie_id">Geometrie</label>
        </div>
        <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
            <?php echo $this->tag->textField(array("geometrie_id", "type" => "number")) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
            <label for="vue_validation">Vue Of Validation</label>
        </div>
        <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
            <?php echo $this->tag->textField(array("vue_validation", "size" => 30)) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
            <label for="mf_layer_name">Mf Of Layer Of Name</label>
        </div>
        <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
            <?php echo $this->tag->textField(array("mf_layer_name", "size" => 30)) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
            <label for="mf_layer_group">Mf Of Layer Of Group</label>
        </div>
        <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
            <?php echo $this->tag->textField(array("mf_layer_group", "size" => 30)) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
            <label for="mf_layer_meta_name">Mf Of Layer Of Meta Of Name</label>
        </div>
        <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
            <?php echo $this->tag->textField(array("mf_layer_meta_name", "size" => 30)) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
            <label for="mf_layer_filtre">Mf Of Layer Of Filtre</label>
        </div>
        <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
            <?php echo $this->tag->textField(array("mf_layer_filtre", "size" => 30)) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
            <label for="mf_layer_minscale_denom">Mf Of Layer Of Minscale Of Denom</label>
        </div>
        <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
            <?php echo $this->tag->textField(array("mf_layer_minscale_denom", "type" => "number")) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
            <label for="mf_layer_maxscale_denom">Mf Of Layer Of Maxscale Of Denom</label>
        </div>
        <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
            <?php echo $this->tag->textField(array("mf_layer_maxscale_denom", "type" => "number")) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
            <label for="mf_layer_labelminscale_denom">Mf Of Layer Of Labelminscale Of Denom</label>
        </div>
        <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
            <?php echo $this->tag->textField(array("mf_layer_labelminscale_denom", "type" => "number")) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
            <label for="mf_layer_labelmaxscale_denom">Mf Of Layer Of Labelmaxscale Of Denom</label>
        </div>
        <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
            <?php echo $this->tag->textField(array("mf_layer_labelmaxscale_denom", "type" => "number")) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
            <label for="mf_layer_def">Mf Of Layer Of Def</label>
        </div>
        <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
            <?php echo $this->tag->textField(array("mf_layer_def", "size" => 30)) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
            <label for="mf_layer_meta_def">Mf Of Layer Of Meta Of Def</label>
        </div>
        <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
            <?php echo $this->tag->textField(array("mf_layer_meta_def", "size" => 30)) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
            <label for="service_tuile">Service Of Tuile</label>
        </div>
        <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
            <?php echo $this->tag->textField(array("service_tuile", "size" => 30)) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
            <label for="catalogue_csw_id">Catalogue Of Csw</label>
        </div>
        <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
            <?php echo $this->tag->textField(array("catalogue_csw_id", "type" => "number")) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
            <label for="fiche_csw_id">Fiche Of Csw</label>
        </div>
        <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
            <?php echo $this->tag->textField(array("fiche_csw_id", "size" => 30)) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
            <label for="mf_layer_meta_wfs_max_feature">Mf Of Layer Of Meta Of Wfs Of Max Of Feature</label>
        </div>
        <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
            <?php echo $this->tag->textField(array("mf_layer_meta_wfs_max_feature", "type" => "number")) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
            <label for="est_fond_de_carte">Est Of Fond Of De Of Carte</label>
        </div>
        <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
            <?php echo $this->tag->textField(array("est_fond_de_carte", "size" => 30)) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
            <label for="mf_layer_opacity">Mf Of Layer Of Opacity</label>
        </div>
        <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
            <?php echo $this->tag->textField(array("mf_layer_opacity", "type" => "number")) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
            <label for="mf_layer_meta_title">Mf Of Layer Of Meta Of Title</label>
        </div>
        <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
            <?php echo $this->tag->textField(array("mf_layer_meta_title", "size" => 30)) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
            <label for="mf_layer_meta_group_title">Mf Of Layer Of Meta Of Group Of Title</label>
        </div>
        <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
            <?php echo $this->tag->textField(array("mf_layer_meta_group_title", "size" => 30)) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
            <label for="mf_layer_labelitem">Mf Of Layer Of Labelitem</label>
        </div>
        <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
            <?php echo $this->tag->textField(array("mf_layer_labelitem", "size" => 30)) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
            <label for="mf_layer_meta_z_order">Mf Of Layer Of Meta Of Z Of Order</label>
        </div>
        <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
            <?php echo $this->tag->textField(array("mf_layer_meta_z_order", "type" => "number")) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
            <label for="print_option_url">Print Of Option Of Url</label>
        </div>
        <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
            <?php echo $this->tag->textField(array("print_option_url", "size" => 30)) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
            <label for="print_option_layer_name">Print Of Option Of Layer Of Name</label>
        </div>
        <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
            <?php echo $this->tag->textField(array("print_option_layer_name", "size" => 30)) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
            <label for="est_commune">Est Of Commune</label>
        </div>
        <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
            <?php echo $this->tag->textField(array("est_commune", "size" => 30)) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
            <label for="est_publique">Est Of Publique</label>
        </div>
        <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
            <?php echo $this->tag->textField(array("est_publique", "size" => 30)) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
            <label for="layer_a_order">Layer Of A Of Order</label>
        </div>
        <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
            <?php echo $this->tag->textField(array("layer_a_order", "type" => "number")) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
            <label for="max_zoom_level">Max Of Zoom Of Level</label>
        </div>
        <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
            <?php echo $this->tag->textField(array("max_zoom_level", "type" => "number")) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
            <label for="min_zoom_level">Min Of Zoom Of Level</label>
        </div>
        <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
            <?php echo $this->tag->textField(array("min_zoom_level", "type" => "number")) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
            <label for="classe_entite_id">Classe Of Entite</label>
        </div>
        <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
            <?php echo $this->tag->textField(array("classe_entite_id", "type" => "number")) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
            <label for="geometrie_type_id">Geometrie Of Type</label>
        </div>
        <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
            <?php echo $this->tag->textField(array("geometrie_type_id", "type" => "number")) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
            <label for="vue_defaut">Vue Of Defaut</label>
        </div>
        <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
            <?php echo $this->tag->textField(array("vue_defaut", "size" => 30)) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
            <label for="date_chargement">Date Of Chargement</label>
        </div>
        <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
            <?php echo $this->tag->textField(array("date_chargement", "size" => 30)) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
            <label for="connexion_id">Connexion</label>
        </div>
        <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
            <?php echo $this->tag->textField(array("connexion_id", "type" => "number")) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
            <label for="echelle_prod">Echelle Of Prod</label>
        </div>
        <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
            <?php echo $this->tag->textField(array("echelle_prod", "size" => 30)) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
            <label for="remarque_geometrie">Remarque Of Geometrie</label>
        </div>
        <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
            <?php echo $this->tag->textField(array("remarque_geometrie", "size" => 30)) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
            <label for="ind_inclusion">Ind Of Inclusion</label>
        </div>
        <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
            <?php echo $this->tag->textField(array("ind_inclusion", "size" => 30)) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
            <label for="mf_layer_data">Mf Of Layer Of Data</label>
        </div>
        <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
            <?php echo $this->tag->textField(array("mf_layer_data", "size" => 30)) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
            <label for="mf_layer_projection">Mf Of Layer Of Projection</label>
        </div>
        <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
            <?php echo $this->tag->textField(array("mf_layer_projection", "size" => 30)) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
            <label for="acces">Acces</label>
        </div>
        <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
            <?php echo $this->tag->textField(array("acces", "size" => 30)) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
            <label for="nom_classe_entite">Nom Of Classe Of Entite</label>
        </div>
        <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
            <?php echo $this->tag->textField(array("nom_classe_entite", "size" => 30)) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
            <label for="description_classe_entite">Description Of Classe Of Entite</label>
        </div>
        <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
            <?php echo $this->tag->textField(array("description_classe_entite", "size" => 30)) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
            <label for="source_entite_id">Source Of Entite</label>
        </div>
        <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
            <?php echo $this->tag->textField(array("source_entite_id", "type" => "number")) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
            <label for="classification_id">Classification</label>
        </div>
        <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
            <?php echo $this->tag->textField(array("classification_id", "type" => "number")) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
            <label for="organisme_responsable_id">Organisme Of Responsable</label>
        </div>
        <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
            <?php echo $this->tag->textField(array("organisme_responsable_id", "type" => "number")) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
            <label for="contact_id">Contact</label>
        </div>
        <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
            <?php echo $this->tag->textField(array("contact_id", "type" => "number")) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
            <label for="remarque_classe_entite">Remarque Of Classe Of Entite</label>
        </div>
        <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
            <?php echo $this->tag->textField(array("remarque_classe_entite", "size" => 30)) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
            <label for="nom_connexion">Nom Of Connexion</label>
        </div>
        <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
            <?php echo $this->tag->textField(array("nom_connexion", "size" => 30)) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
            <label for="connexion">Connexion</label>
        </div>
        <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
            <?php echo $this->tag->textField(array("connexion", "size" => 30)) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
            <label for="connexion_type_id">Connexion Of Type</label>
        </div>
        <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
            <?php echo $this->tag->textField(array("connexion_type_id", "type" => "number")) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
            <label for="nom_connexion_type">Nom Of Connexion Of Type</label>
        </div>
        <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
            <?php echo $this->tag->textField(array("nom_connexion_type", "size" => 30)) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
            <label for="connexion_type">Connexion Of Type</label>
        </div>
        <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
            <?php echo $this->tag->textField(array("connexion_type", "size" => 30)) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
            <label for="nom_geometrie_type">Nom Of Geometrie Of Type</label>
        </div>
        <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
            <?php echo $this->tag->textField(array("nom_geometrie_type", "size" => 30)) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
            <label for="layer_type">Layer Of Type</label>
        </div>
        <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
            <?php echo $this->tag->textField(array("layer_type", "size" => 30)) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
            <label for="geometrie_type">Geometrie Of Type</label>
        </div>
        <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
            <?php echo $this->tag->textField(array("geometrie_type", "size" => 30)) ?>
        </div>
    </div>
