
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="couche_id">Couche</label>
    </div>
    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
        <?php
        echo $this->tag->select(array(
            "couche_id",
            IgoCouche::find(array("order" => "mf_layer_name")),
            "using" => array("id", "mf_layer_name"),
            "emptyText" => "Choisir...",
            "useEmpty" => true))
        ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="mf_class_def">Class Of Def</label>
    </div>
    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
<?php echo $this->tag->textArea(array('mf_class_def', 'cols' => 80, 'rows' => 20)) ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="mf_class_z_order">Ordre</label>
    </div>
    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
<?php echo $this->tag->textField(array("mf_class_z_order", "size" => 10)) ?>
    </div>
</div>
<?php $this->partial("commun/date_modification"); ?>