
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="nom">Nom<span class="glyphicon glyphicon-asterisk oblig"></span></label>
    </div>
    <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
        <?php echo $this->tag->textField(array(
                "nom", 
                "class" => "form-control"
            ));
        ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="layer_type">Code LayerType</label>
    </div>
    <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
        <?php echo $this->tag->textField(array(
                "layer_type", 
                "class" => "form-control"
            )); 
        ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="geometrie_type">Type de géométrie<span class="glyphicon glyphicon-asterisk oblig"></span></label>
    </div>
    <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
        <?php
        echo $this->tag->select(array(
            "geometrie_type",
            ($this->view->getActionName() == "index") ?
                    array(
                "" => " ",
                "C" => "Chart",
                "Q" => "Query",
                "R" => "Raster",
                "V" => "Vectoriel") :
                    array(
                "C" => "Chart",
                "Q" => "Query",
                "R" => "Raster",
                "V" => "Vectoriel"),
            "class" => "form-control",
            ));
        ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="mf_layer_meta_z_order">Ordre Zs</label>
    </div>
    <div class="col-lg-2 col-md-3 col-sm-4 col-xs-12">
        <?php echo $this->tag->textField(array(
                "mf_layer_meta_z_order", 
                "class" => "form-control"
            ));
        ?>
    </div>
</div>
<?php $this->partial("commun/date_modification"); ?>
