<?php use Phalcon\Tag; ?>
<?php echo $this->getContent(); ?>
<?php $this->partial("commun/titre", array("titre" =>"Permissions sur les services")) ?>
<?php $this->partial("commun/search_entete") ?>

<table class="table table-striped table-search">
    <thead>
        <tr>
            <th>Profil</th>
            <th>Service</th>
            <th><?php echo $this->tag->linkTo("igo_service_profil/search?order=date_modif", "Date de modification <span class='glyphicon glyphicon-resize-vertical'></span>") ?></th>
            <th class="editer"></th>
            <th class="detruire"></th>   
        </tr>
    </thead>
    <tbody>
    <?php foreach ($page->items as $igo_service_profil) { ?>
        <tr>
             <td><?php  if ($igo_service_profil->IgoProfil){echo $igo_service_profil->IgoProfil->libelle;} ?></td>
              <td><?php  if ($igo_service_profil->IgoService){echo $igo_service_profil->IgoService->nom;} ?></td>
            <td><?php echo $igo_service_profil->date_modif ?></td>
            <td><?php echo $this->tag->linkTo(array("igo_service_profil/edit/" . $igo_service_profil->profil_id."/".$r_controller."/".$action."/".$parameters, "<span class='glyphicon glyphicon-pencil' aria-hidden='true'></span> Modifier")); ?></td>
            <td><?php echo $this->tag->linkTo(array("igo_service_profil/delete/" . $igo_service_profil->profil_id."/".$r_controller."/".$action."/".$parameters, "<span class='glyphicon glyphicon-trash' aria-hidden='true'></span> Détruire", 'data-confirmation'=>'supprimer')); ?></td>
        </tr>
    <?php } ?>
    </tbody>
</table>
<?php $this->partial("commun/search_pagination") ?>