
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="profil_id">Profil<span class="glyphicon glyphicon-asterisk oblig"></span></label>
    </div>
    <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
        <?php
        if ($this->session->has("profil_id")) {
            $this->tag->setDefault("profil_id", $this->session->get("profil_id"));
        }
        ?>
        <?php
        echo $this->tag->select(array(
            "profil_id",
            IgoProfil::find(array("order" => "libelle")),
            "using" => array("id", "libelle"),
            "emptyText" => "Choisir...",
            "useEmpty" => true,
            "class" => "form-control"
            ));
        ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="service_id">Service<span class="glyphicon glyphicon-asterisk oblig"></span></label>
    </div>
    <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
        <?php
        echo $this->tag->select(array(
            "service_id",
            IgoService::find(array("order" => "nom")),
            "using" => array("id", "nom"),
            "emptyText" => "Choisir...",
            "useEmpty" => true,
            "class" => "form-control"
            ));
        ?>
    </div>
</div>
<?php $this->partial("commun/date_modification"); ?>