<?php echo \Phalcon\Tag::javascriptInclude("js/gestion_couche_creation.js"); ?>
<script>
var geometrie_type_id=[];
var geometrie_type=[];

var connexion_type_id=[];
var connexion_type_vue=[];
var connexion_type_data=[];
var connexion_type_projection=[];
$(document).ready(function(){
   
    <?php
        $geometrie_type= IgoGeometrieType::find();
        foreach ($geometrie_type as $value) {
           echo "geometrie_type_id.push(".$value->id.");\n";
           echo "geometrie_type.push('".$value->geometrie_type."');\n";
        }
    ?>
   
    <?php
        $connexion_type= IgoConnexionType::find();
        foreach ($connexion_type as $value) {
           echo "connexion_type_id.push('".$value->id."');\n";
           echo "connexion_type_vue.push(".($value->ind_vue?'true':'false').");\n";
           echo "connexion_type_data.push(".($value->ind_data?'true':'false').");\n";
           echo "connexion_type_projection.push(".($value->ind_projection?'true':'false').");\n";
        }
    ?>
    
    $('#vue-avancee').click(function(){
        if($(this).prop('checked')){
            afficher('vue-avancee');       
        }else{
            cacher('vue-avancee');
        }
        
    });
    
    $("#geometrie_type_id").change(function(e){
        var geometrieType= $('#geometrie_type_id option:selected').text();
        changeGeometrie(geometrieType);
    });
    
    $('#connexion_type_id_vertoriel').change(function(e){
        var connexion_type= $('#connexion_type_id_vertoriel').val();
        changeConnexion(connexion_type);
    });

    $('#connexion_type_id_raster').change(function(e){
        var connexion_type= $('#connexion_type_id_raster').val();
        changeConnexion(connexion_type);
    });
   $('#connexion_type_id_chart').change(function(e){
        var connexion_type= $('#connexion_type_id_chart').val();
        changeConnexion(connexion_type);
    });
    $('#connexion_type_id_query').change(function(e){
        var connexion_type= $('#connexion_type_id_query').val();
        changeConnexion(connexion_type);
    });
    
     $('#vue-avancee').triggerHandler('click');
     $('#geometrie_type_id').triggerHandler('change');
     
     $('*[data-toggle="tooltip"]').tooltip({html: true});
});
</script>
<?php $this->partial("commun/new", array( "titre" =>"Création rapide d'une couche")) ?>
