<style>
    .btn-retour{
        display:none;
    }
    
</style>
<script>
    $(document).ready(function(){
      $("form").submit(function(e){
        alert("Sauvegarde en cours...");
        alert("C'est enregistré.");
        alert("C'est un démo. Ça ne fonctionne pas vraiment.");
        e.preventDefault();
        return false;
    });  
        
    });

</script>
<?php echo $this->getContent(); ?>
 <div class="panel-group" id="accordion">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
          Classe entité
        </a>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse in">
      <div class="panel-body">  
<?php  echo $this->view->includeCTL("igo_classe_entite","edit?".$classe_entite_id); ?>
 </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
          Connexion
        </a>
      </h4>
    </div>
    <div id="collapseTwo" class="panel-collapse collapse">
      <div class="panel-body">
<?php  echo $this->view->includeCTL("igo_connexion","edit?".$connexion_id); ?>
 </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseTree">
          Géométrie
        </a>
      </h4>
    </div>
    <div id="collapseTree" class="panel-collapse collapse">
      <div class="panel-body">
<?php  echo $this->view->includeCTL("igo_geometrie","edit?".$geometrie_id,$r_controller); ?>
 </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseFour">
          Couche
        </a>
      </h4>
    </div>
    <div id="collapseFour" class="panel-collapse collapse">
      <div class="panel-body">
<?php  echo $this->view->includeCTL("igo_couche","edit?".$id,$r_controller); ?>       </div>
    </div>
  </div>
</div>