<?php echo $this->tag->form("gestion_couche/traiteMapfile") ?>

<?php $this->partial("commun/titre", array("titre" =>"Charger une définition de LAYER")) ?>

    <div class="row"> 
        <div class="col-lg-10 col-lg-offset-1 text-center">
            <?php echo $this->tag->textArea(array(
                    'code', 
                    'cols' => 120, 
                    'rows' => 40, 
                    "class" => "form-control"
                )); 
            ?>
        </div>
    </div>
    <div class="row"> 
        <div class="text-center">
        <div class="text-center"><?php echo $this->tag->submitButton(array("Traiter", "class" => 'btn btn-primary')) ?></div>
        </div>
    </div>
    <?php echo $this->tag->hiddenField("id") ?>
    <input type='hidden' id="r_parameters" name="r_parameters" value="<?php echo $parameters ?>"/>

</form>