<?php
define("TOOLTIP_CONNECTION_TYPE", "LAYER<div class='tab'><span class='actif'>CONNECTIONTYPE {type_connexion}</span></div>END");
?>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right"><h4>Géométrie</h4></div>
</div>
<?php //champ classe_entite_id de igo_geometrie ?>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="classe_entite_id">Nom de la classe entitée<span class="glyphicon glyphicon-asterisk oblig"></span></label>
    </div>
    <div class="col-lg-7 col-md-7 col-sm-7 col-xs-12">
        <?php
        echo $this->tag->select(array(
            "classe_entite_id",
            IgoClasseEntite::find(array("order" => "nom")),
            "using" => array("id", "nom"),
            "emptyText" => "Choisir...",
            "useEmpty" => true,
            "class" => "form-control",
            "data-toggle" => "tooltip",
            "data-placement" => "right",
            "title" => "LAYER<div class='tab'>METADATA<div class='tab'><span class='actif'>\"wms_name\" \"{nom_classe_entite}\"</span></div>END</div>END"));
        ?> 
    </div>
    <div class="col-lg-1 col-md-1 col-sm-1">
         <?php echo $this->tag->linkTo(array("igo_classe_entite/new" . "/" . $r_controller . "/" . $action . "/" . $parameters, "Créer", 'class'=>'creer')); ?>
        <?php //echo $this->tag->linkTo(array("igo_classe_entite/edit" . "/" . $this->tag->getValue("classe_entite_id") . "/" . $r_controller . "/" . $action . "/" . $parameters, "Éditer")); ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="geometrie_type_id">Type de géométrie<span class="glyphicon glyphicon-asterisk oblig"></span></label>
    </div>
    <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
        <?php
        echo $this->tag->select(array(
            "geometrie_type_id",
            IgoGeometrieType::find(array("order" => "nom")),
            "using" => array("id", "nom"),
            "emptyText" => "Choisir...",
            "useEmpty" => true,
            "class" => "form-control",
            "data-toggle" => "tooltip",
            "data-placement" => "right",
            "title" => "LAYER<div class='tab'><span class='actif'>TYPE {type_geometrie}</span></div>END"));
        ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="acces">Point d'accès<span class="glyphicon glyphicon-asterisk oblig"></span></label>
    </div>
    <div class="col-lg-2 col-md-2 col-sm-2 col-xs-12">
        <?php echo $this->tag->select(array(
                "acces", 
                ($this->view->getActionName() == "index") ? 
                    array("D" => "Distant", 
                          "L" => "Local") : 
                    array("D" => "Distant", 
                          "L" => "Local"),
                "class" => "form-control")); ?>
    </div>
</div>
<?php //champ mf_layer_data de igo_geometrie ?>
<div class="row" data-toggle="data" data-acces-type="L">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="mf_layer_data">Chemin d'accès des données</label>
    </div>
    <div class="col-lg-7 col-md-7 col-sm-7 col-xs-12">
        <?php
        echo $this->tag->textField(array(
            "mf_layer_data",
            "class" => "form-control",
            "placeholder" => "Ex : Vigilance/Inondation-crue/Instruments de surveillance",
            "data-toggle" => "tooltip",
            "data-placement" => "right",
            "title" => "LAYER<div class='tab'><span class='actif'>DATA \"{chemin_acces_donnees}\"</span></div>END"));
        ?>
    </div>
</div>
<div class="row" data-toggle="projection" data-acces-type="L">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="mf_layer_projection">Projection<span class="glyphicon glyphicon-asterisk oblig"></span></label>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
        <?php
        echo $this->tag->textField(array(
            "mf_layer_projection",
            "class" => "form-control",
            "placeholder" => "Ex : init=epsg:32198",
            "data-toggle" => "tooltip",
            "data-placement" => "right",
            "title" => "LAYER<div class='tab'>PROJECTION<div class='tab'><span class='actif'>\"{projection}\"</span></div>END</div>END"
        ));
        ?>
    </div>
</div>
<div class="row" data-acces-type="L">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="connexion_id">Inclusion des attributs</label>
    </div>
    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
        <?php
        echo $this->tag->select(array(
            "id_ici",
            IgoGroupe::find(array("order" => "nom")),
            "using" => array("id", "nom"),
            "emptyText" => "Choisir...",
            "useEmpty" => true,
            "class" => "form-control"));
        ?>
    </div>Reste à définir comment on gère l'inclusion des attributs
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right"><h4>Connexion</h4></div>
</div>
<div class="row" data-toggle="vectoriel">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="connexion_type_id_vertoriel">Type de connexion<span class="glyphicon glyphicon-asterisk oblig"></span></label>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
        <?php
        echo $this->tag->select(array(
            "connexion_type_id_vertoriel",
            "name" => "connexion_type_id",
            IgoConnexionType::find(array("geometrie_type='V'", "order" => "nom")),
            "using" => array("id", "nom"),
            "emptyText" => "Choisir...",
            "useEmpty" => true,
            "class" => "form-control",
            "data-toggle" => "tooltip",
            "data-placement" => "right",
            "title" => TOOLTIP_CONNECTION_TYPE));
        ?>
    </div>
</div>
<div class="row" data-toggle="raster">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="connexion_type_id_raster">Type de connexion<span class="glyphicon glyphicon-asterisk oblig"></span></label>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
        <?php
        echo $this->tag->select(array(
            "connexion_type_id_raster",
            "name" => "connexion_type_id",
            IgoConnexionType::find(array("geometrie_type='R'", "order" => "nom")),
            "using" => array("id", "nom"),
            "emptyText" => "Choisir...",
            "useEmpty" => true,
            "class" => "form-control",
            "data-toggle" => "tooltip",
            "data-placement" => "right",
            "title" => TOOLTIP_CONNECTION_TYPE));
        ?>
    </div>
</div>
<div class="row" data-toggle="chart">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="connexion_type_id_chart">Type de connexion<span class="glyphicon glyphicon-asterisk oblig"></span></label>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
        <?php
        echo $this->tag->select(array(
            "connexion_type_id_chart",
            "name" => "connexion_type_id",
            IgoConnexionType::find(array("geometrie_type='C'", "order" => "nom")),
            "using" => array("id", "nom"),
            "emptyText" => "Choisir...",
            "useEmpty" => true,
            "class" => "form-control",
            "data-toggle" => "tooltip",
            "data-placement" => "right",
            "title" => TOOLTIP_CONNECTION_TYPE));
        ?>
    </div>
</div>
<div class="row" data-toggle="query">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="connexion_type_id_query">Type de connexion<span class="glyphicon glyphicon-asterisk oblig"></span></label>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
        <?php
        echo $this->tag->select(array(
            "connexion_type_id_query",
            "name" => "connexion_type_id",
            IgoConnexionType::find(array("geometrie_type='Q'", "order" => "nom")),
            "using" => array("id", "nom"),
            "emptyText" => "Choisir...",
            "useEmpty" => true,
            "class" => "form-control",
            "data-toggle" => "tooltip",
            "data-placement" => "right",
            "title" => TOOLTIP_CONNECTION_TYPE));
        ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right"><h4>Couche</h4></div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="mf_layer_name">Nom de code<span class="glyphicon glyphicon-asterisk oblig"></span></label>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
        <?php
        echo $this->tag->textField(array(
            "mf_layer_name",
            "class" => "form-control",
            "data-toggle" => "tooltip",
            "data-placement" => "right",
            "title" => "LAYER<div class='tab'><span class='actif'>NAME \"{nom_code}\"</span></div>END"));
        ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="mf_layer_meta_title">Titre<span class="glyphicon glyphicon-asterisk oblig"></span></label>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
        <?php
        echo $this->tag->textField(array(
            "mf_layer_meta_title",
            "class" => "form-control",
            "data-toggle" => "tooltip",
            "data-placement" => "right",
            "title" => "LAYER<div class='tab'>METADATA<div class='tab'><span class='actif'>\"wms_title\" \"{titre}\"</div>END</div>END"));
        ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="mf_layer_group">Code de groupe</label>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
        <?php
        echo $this->tag->textField(array(
            "mf_layer_group",
            "class" => "form-control",
            "placeholder" => "Ex : chemin/vers/le/groupe/nom_du_groupe",
            "data-toggle" => "tooltip",
            "data-placement" => "right",
            "title" => "LAYER<div class='tab'><span class='actif'>GROUP \"{code_groupe}\"</span></div>END"));
        ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="mf_layer_meta_group_title">Hiérarchie et/ou titre du groupe</label>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
        <?php
        echo $this->tag->textField(array(
            "mf_layer_meta_group_title",
            "class" => "form-control",
            "data-toggle" => "tooltip",
            "data-placement" => "right",
            "title" => "LAYER<div class='tab'>METADATA<div class='tab'><span class='actif'>\"wms_group_title\" \"{titre_groupe}\"</span></div>END</span></div>END"));
        ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="fiche_csw_id">Id de fiche de métadonnées (catalogue CSW)</label>
    </div>
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
        <?php
        echo $this->tag->textField(array(
            "fiche_csw_id",
            "class" => "form-control",
            "placeholder" => "Ex : 557940e9-5dfa-4a92-a140-8afd1618975d"));
        ?>
    </div>
</div>
<div class="row" data-acces-type="L">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="mf_layer_minscale_denom">Échelle minimale d'affichage</label>
    </div>
    <div class="col-lg-2 col-md-3 col-sm-3 col-xs-12">
        <?php
        echo $this->tag->textField(array(
            "mf_layer_minscale_denom",
            "type" => "number",
            "placeholder" => "Ex : 2",
            "class" => "form-control",
            "data-toggle" => "tooltip",
            "data-placement" => "right",
            "title" => "LAYER<div class='tab'><span class='actif'>MINSCALE {min}</span></div>END"));
        ?>
    </div>
</div>
<div class="row" data-acces-type="L">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="mf_layer_maxscale_denom">Échelle maximale d'affichage</label>
    </div>
    <div class="col-lg-2 col-md-3 col-sm-3 col-xs-12">
        <?php
        echo $this->tag->textField(array(
            "mf_layer_maxscale_denom",
            "type" => "number",
            "placeholder" => "Ex : 8",
            "class" => "form-control",
            "data-toggle" => "tooltip",
            "data-placement" => "right",
            "title" => "LAYER<div class='tab'><span class='actif'>MAXSCALE {max}</span></div>END"));
        ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="mf_layer_opacity">Opacité</label>
    </div>
    <div class="col-lg-2 col-md-3 col-sm-3 col-xs-12">
        <?php
        echo $this->tag->textField(array(
            "mf_layer_opacity",
            "type" => "number",
            "placeholder" => "Ex : 80",
            "class" => "form-control",
            "data-toggle" => "tooltip",
            "data-placement" => "right",
            "title" => "LAYER<div class='tab'>CLASS<div class='tab'>STYLE<div class='tab'><span class='actif'>OPACITY {opacite}</span></div>END</div>END</div>END"));
        ?>
    </div>
</div>
<div class="row" data-acces-type="L">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right"><h4>Classe</h4></div>
</div>
<?php //champ mf_class_def de igo_classe ?>
<div class="row" data-acces-type="L">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="mf_class_def">Mf Class Of Def</label>
    </div>
    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
        <?php
        echo $this->tag->textArea(array(
            'mf_class_def',
            "class" => "form-control",
            'cols' => 80,
            'rows' => 20,
            "data-toggle" => "tooltip",
            "data-placement" => "right",
            "title" => "LAYER<div class='tab'>CLASS<div class='tab actif'>{class_def}</div>END</div>END"));
        ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
    </div>
    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
        <?php echo $this->tag->checkField(array('vue-avancee', "value" => '1')); ?>
        <label for="vue-avancee">Afficher les options avancées</label>
    </div>
</div>
<div class="row" data-toggle="vue-avancee">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right"><h4>Couche</h4></div>
</div>
<div class="row" data-toggle="vue-avancee" data-acces-type="L">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="mf_layer_labelminscale_denom">Échelle minimale d'affichage des étiquettes</label>
    </div>
    <div class="col-lg-2 col-md-3 col-sm-3 col-xs-12">
        <?php
        echo $this->tag->textField(array(
            "mf_layer_labelminscale_denom",
            "type" => "number",
            "placeholder" => "Ex : 2",
            "class" => "form-control",
            "data-toggle" => "tooltip",
            "data-placement" => "right",
            "title" => "LAYER<div class='tab'><span class='actif'>LABELMINSCALE {min}</span></div>END"));
        ?>
    </div>
</div>
<div class="row" data-toggle="vue-avancee" data-acces-type="L">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="mf_layer_labelmaxscale_denom">Échelle maximale d'affichage des étiquettes</label>
    </div>
    <div class="col-lg-2 col-md-3 col-sm-3 col-xs-12">
        <?php
        echo $this->tag->textField(array(
            "mf_layer_labelmaxscale_denom",
            "type" => "number",
            "placeholder" => "Ex : 10",
            "class" => "form-control",
            "data-toggle" => "tooltip",
            "data-placement" => "right",
            "title" => "LAYER<div class='tab'><span class='actif'>LABELMAXSCALE {max}</span></div>END"));
        ?>
    </div>
</div>
<div class="row" data-toggle="vue-avancee" data-acces-type="L">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="mf_layer_meta_wfs_max_feature">Nombre maximale d'éléments WFS</label>
    </div>
    <div class="col-lg-2 col-md-3 col-sm-3 col-xs-12">
        <?php
        echo $this->tag->textField(array(
            "mf_layer_meta_wfs_max_feature",
            "type" => "number",
            "placeholder" => "Ex : 500",
            "class" => "form-control",
            "data-toggle" => "tooltip",
            "data-placement" => "right",
            "title" => "LAYER<div class='tab'>METADATA<div class='tab actif'>\"wfs_maxfeatures\" {max}</div>END</div>END"));
        ?>
    </div>
</div>
<div class="row" data-toggle="vue-avancee" data-acces-type="L">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="mf_layer_labelitem">Nom de l'attribut d'affichage des étiquettes</label>
    </div>
    <div class="col-lg-2 col-md-3 col-sm-4 col-xs-12">
        <?php
        echo $this->tag->textField(array(
            "mf_layer_labelitem",
            "class" => "form-control",
            "data-toggle" => "tooltip",
            "data-placement" => "right",
            "title" => "LAYER<div class='tab'><span class='actif'>LABELITEM \"{nom_attribut_affichage}\"</span></div>END"));
        ?>
    </div>
</div>
<div class="row" data-toggle="vue-avancee" data-acces-type="L">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="mf_layer_def">Mf Of Layer Of Def</label>
    </div>
    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
        <?php
        echo $this->tag->textArea(array(
            'mf_layer_def',
            "class" => "form-control",
            'cols' => 50,
            'rows' => 10,
            "data-toggle" => "tooltip",
            "data-placement" => "right",
            "title" => "LAYER<div class='tab actif'>{layer_def}</div>END"));
        ?>
    </div>
</div>
<div class="row" data-toggle="vue-avancee" data-acces-type="L">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="mf_layer_meta_def">Mf Of Layer Of Meta Of Def</label>
    </div>
    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
        <?php
        echo $this->tag->textArea(array(
            'mf_layer_meta_def',
            "class" => "form-control",
            'cols' => 50,
            'rows' => 5,
            "data-toggle" => "tooltip",
            "data-placement" => "right",
            "title" => "LAYER<div class='tab'>METADATA<div class='tab actif'>{layer_meta_def}</div>END</div>END"));
        ?>
    </div>
</div>
<div class="row" data-toggle="vue-avancee">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="mf_layer_meta_z_order">Ordre (affichage ou bien arbo???)</label>
    </div>
    <div class="col-lg-2 col-md-3 col-sm-3 col-xs-12">
        <?php
        echo $this->tag->textField(array(
            "mf_layer_meta_z_order",
            "class" => "form-control",
            "placeholder" => "Ex : 100",
            "data-toggle" => "tooltip",
            "data-placement" => "right",
            "title" => "LAYER<div class='tab'>METADATA<div class='tab actif'>z_order {ordre}</div>END</div>END"));
        ?>
    </div>
</div>
<div class="row" data-toggle="vue-avancee" data-acces-type="L">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="mf_layer_filtre">Condition d'affichage</label>
    </div>
    <div class="col-lg-4 col-md-5 col-sm-6 col-xs-12">
        <?php
        echo $this->tag->textField(array(
            "mf_layer_filtre",
            "class" => "form-control",
            "placeholder" => "Ex : champ_un = \"toto\" AND champ_deux > 100",
            "data-toggle" => "tooltip",
            "data-placement" => "right",
            "title" => "LAYER<div class='tab actif'>FILTER {filtre}</div>END"
        ));
        ?>
    </div>
</div>
<div class="row" data-toggle="vue-avancee">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="groupe_id">Groupe de couches</label>
    </div>
    <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
        <?php
        echo $this->tag->select(array(
            "groupe_id",
            "class" => "form-control",
            IgoGroupe::find(array("order" => "nom")),
            "using" => array("id", "nom"),
            "emptyText" => "Choisir...",
            "useEmpty" => true));
        ?>
    </div>
    <div class="col-lg-1 col-md-1 col-sm-1"> 
        <?php
        echo $this->tag->linkTo(array(
            "igo_groupe/new" . "/" . $r_controller . "/" . $action . "/" . $parameters,
            "Créer"));
        ?>
    </div>
</div>
<div class="row" data-toggle="est-fond-carte vue-avancee">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="est_fond_de_carte">Fond de carte</label>
    </div>
    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
        <?php echo $this->tag->checkField(array("est_fond_de_carte", "value" => 1)); ?>

    </div>
</div>
<div class="row" data-toggle="vue vue-avancee" data-acces-type="L">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="vue_validation">Vue de validation</label>
    </div>
    <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
        <?php
        echo $this->tag->textField(array(
            "vue_validation",
            "class" => "form-control"
        ));
        ?>
    </div>
</div>
<div class="row" data-toggle="vue-avancee">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="description">Description</label>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
        <?php
        echo $this->tag->textField(array(
            "description",
            "class" => "form-control",
            "data-toggle" => "tooltip",
            "data-placement" => "right",
            "title" => "Description textuelle de la couche. Utilisée dans l'outil de gestion uniquement."));
        ?>
    </div>
</div>
<?php echo $this->tag->hiddenField(array('connexion_type_id')); ?>
<?php echo $this->tag->hiddenField(array('connexion_id')); ?>
<?php echo $this->tag->hiddenField(array('mf_layer_filter')); ?>
<?php echo $this->tag->hiddenField(array('z_order')); ?>