<?php echo $this->getContent(); ?>
<div class="row">
    <div class="col-lg-8 col-lg-offset-4 col-md-8 col-md-offset-4 col-sm-8 col-sm-offset-4 col-xs-12 text-left">
        <h3><?php echo $titre;?></h3>
    </div>
</div>
<?php echo $this->tag->form($controller . "/submit/") ?><!-- <form>-->
    <div class="row">
        <div class="col col-lg-4 text-right">
            <label for='idContexte'>Contexte<span class="glyphicon glyphicon-asterisk oblig"></span></label>
        </div>
        <div class="col col-lg-6"> 
        <?php echo $formulaire->render('idContexte');?>
        </div>
    </div>    
    <div class="row">
        <div class="col col-lg-4 text-right">
            <label for='idProfil'>Profil<span class="glyphicon glyphicon-asterisk oblig"></span></label>
        </div>
        <div class="col col-lg-6">   
            <?php echo $formulaire->render('idProfil');?>
        </div>
    </div>  
    <div class="row">
        <div class="col col-lg-6 col-lg-offset-4">
            <input type="submit" value="Associer toutes les permissions" class="btn btn-primary">
        </div>
    </div>
</form>


