<?php echo $this->getContent(); ?>
<div class="row">
    <div class="col-lg-8 col-lg-offset-4 col-md-8 col-md-offset-4 col-sm-8 col-sm-offset-4 col-xs-12 text-left">
        <h3><?php echo $titre;?></h3>
    </div>
</div>
<div class="row">
    <div class="col-lg-8 col-lg-offset-4 col-md-8 col-md-offset-4 col-sm-8 col-sm-offset-4 col-xs-12 text-left">
        <p><?php echo $message;?></p>
        <?php echo Phalcon\Tag::linkTo(array("igo_permission/arbreCouches/{$idProfil}", "<button class='btn btn-primary'>Accéder au profil</button>"));?>
    </div>
</div>

