
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="nom">Nom<span class="glyphicon glyphicon-asterisk oblig"></span></label>
    </div>
    <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
        <?php echo $this->tag->textField(array(
                "nom", 
                "class" => "form-control"
            )); 
        ?>
    </div>
</div>

<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="nom">Administrateur</label>
    </div>
    <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
        <?php echo $this->tag->checkField(array("estAdmin", "value" => 1)) ?>
    </div>
</div>

<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="nom">Pilote</label>
    </div>
    <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
        <?php echo $this->tag->checkField(array("est_pilote", "value" => 1)) ?>
    </div>
</div>

<?php $this->partial("commun/date_modification"); ?>