<?php use Phalcon\Tag; ?>
<?php echo $this->getContent(); ?>
<?php $this->partial("commun/titre", array("titre" =>"Valeurs")) ?>
<?php $this->partial("commun/search_entete") ?>

<table class="table table-striped">
    <thead>
        <tr>
            <th><?php echo $this->tag->linkTo("igo_valeur/search?order=id", "Valeur") ?></th>
            <th><?php echo $this->tag->linkTo("igo_valeur/search?order=description", "Description") ?></th>
            <th>Liste de valeur</th>
            <th>Valeur</th>
            <th><?php echo $this->tag->linkTo("igo_valeur/search?order=date_modif", "Date de modification") ?></th>
         </tr>
    </thead>
    <tbody>
    <?php foreach ($page->items as $igo_valeur) { ?>
        <tr>
            <td><?php echo $igo_valeur->id ?></td>
            <td><?php echo $igo_valeur->description ?></td>
            <td><?php echo $igo_valeur->liste_valeur_id ?></td>
            <td><?php echo $igo_valeur->valeur ?></td>
            <td><?php echo $igo_valeur->date_modif ?></td>
            <td><?php echo $this->tag->linkTo(array("igo_valeur/edit/" . $igo_valeur->id."/".$r_controller."/".$action."/".$parameters, "Editer")); ?></td>
            <td><?php echo $this->tag->linkTo(array("igo_valeur/delete/" . $igo_valeur->id."/".$r_controller."/".$action."/".$parameters, "Détruire", 'data-confirmation'=>'supprimer')); ?></td>
        </tr>
    <?php } ?>
    </tbody>
</table>
<?php $this->partial("commun/search_pagination") ?>
