
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="description">Description</label>
    </div>
    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
        <?php echo $this->tag->textField(array("description", "size" => 30)) ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="liste_valeur_id">Liste de valeur</label>
    </div>
    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
        <?php echo $this->tag->select(array("liste_valeur_id", IgoListeValeur::find(array("order" => "description")), "using" => array("id", "nom"), "emptyText" => "Choisir...", "useEmpty" => true)) ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="valeur">Valeur</label>
    </div>
    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
        <?php echo $this->tag->textField(array("valeur", "size" => 30)) ?>
    </div>
</div>
<?php $this->partial("commun/date_modification"); ?>