<?php

use Phalcon\Tag; ?>

<?php echo \Phalcon\Tag::javascriptInclude("js/arborescence/tree.js"); ?>
<?php echo \Phalcon\Tag::javascriptInclude("js/arborescence/util.js"); ?>
<?php echo \Phalcon\Tag::javascriptInclude("js/arborescence/Arborescence.js"); ?>
<?php echo \Phalcon\Tag::javascriptInclude("js/arborescence/Attribut.js"); ?>
<?php echo \Phalcon\Tag::javascriptInclude("js/arborescence/Attributs.js"); ?>
<?php echo \Phalcon\Tag::javascriptInclude("js/arborescence/Colonne.js"); ?>
<?php echo \Phalcon\Tag::javascriptInclude("js/arborescence/Couche.js"); ?>
<?php echo \Phalcon\Tag::javascriptInclude("js/arborescence/Groupe.js"); ?>
<?php echo \Phalcon\Tag::javascriptInclude("js/arborescence/ListeElement.js"); ?>
<?php echo \Phalcon\Tag::javascriptInclude("js/igo-couche-contexte-arbre-couche-edit.js"); ?>
<?php echo $this->getContent(); ?>

<?php echo $this->tag->form(array("/igo_couche_contexte/arbreCouches/" . $contexte_id, 'id'=>'formArbo')); ?> 
<input type="hidden" id="valeursArbo" name="valeursArbo">

<?php $this->partial("commun/titre", array("titre" =>"Associer des groupes et des couches à un contexte")); ?>

<div class="row">
    <ul class="pager">
        <li><input type="text" id="terme" placeholder="Filtre"><a href="#" id="ouvrirArborescence" class="btn btn-default navbar-btn" data-toggle="tooltip" title="Ouvre l'arborescence aux endroits correspondants au filtre">Ouvrir</a></li>
        <li><a href="#" id="fermerArborescence" class="btn btn-default navbar-btn" data-toggle="tooltip" title="Fermer l'arborescence">Fermer</a></li>
        <li><a href="#" id="selectionnerCommun" class="btn btn-default navbar-btn" data-toggle="tooltip" title="fait quelque chose">Commun</a></li>
        <li><?php echo $this->tag->submitButton(array("Enregistrer", "class"=>"btn btn-primary", "id" =>"enregistrer")); ?></li>
    </ul>
</div>
</form> 
<div class="row text-left">
    <div class="col-lg-10 col-md-10">
        <div id="conteneur-arborescence"><div id="arborescence"></div></div>

    <script>
 
        var arbo = new Arborescence({edition:true});
<?php


$estAdmin = $this->session->get("info_utilisateur")->estAdmin;

$tabCouchesAjoutees = array();
$tabSousGroupes = array();

foreach ($arbre as $key => $item) { 
    
    //Le groupe doit apparaître comme sous-groupe
    if ("G" == $item->type && strpos($item->grp, '_') !== false) {
        
        //Indiquer qu'il ne doit pas s'afficher à la racine
        $tabSousGroupes[$item->grp] = true;
    }
}
foreach ($arbre as $key => $item) {
    
    if ($item->type == "G") {
   
        $estVisible = $item->visible ? true : false;
        $estActif = $item->active ? true : false;
        $associationEstAssociation = $estAdmin || $item->association_est_association;
        
        $attributs = array(
            'visible' => array(
                'valeur' => $estVisible, 
                'association' => $associationEstAssociation
            ),
            'active'=>array(
                'valeur' => $estActif, 
                'association' => $associationEstAssociation
            )
        );

               $a = explode("_", $item->grp);
               $groupe_id = array_pop($a);
         
        $url = ($estVisible || $estActif) ? $this->url->get('igo_groupe/edit/') . $groupe_id .'/igo_couche_contexte/arbreCouches/'.$contexte_id : '';
        $nom = $item->mf_layer_meta_group_title ? $item->mf_layer_meta_group_title : $item->nom;
        $nom = htmlentities($nom, ENT_QUOTES, 'UTF-8');

        $ordre = $item->layer_a_order ? $item->layer_a_order : 1;

        $idPourGroupe = $item->grp;
        $idParentPourGroupe = Arborescence::idUniquePourGroupeParent($item->grp);
        
        echo "var groupe{$idPourGroupe} = new Groupe('{$idPourGroupe}','{$item->id}_{$idPourGroupe}', '{$nom}', '{$url}', {$ordre}, " . json_encode($attributs) . ");\n";
        
        //Le groupe n'est pas à la racine
        if (strpos($item->grp, '_') !== false ) {
        
            echo "groupe{$idParentPourGroupe}.ajouterGroupe(groupe{$idPourGroupe});\n";
            
        //Le groupe est à la racine
        } else {
            
            //Ce n'est pas un sous-groupe et il n'a pas déjà été ajouté ailleurs
            if (!isset($tabSousGroupes[$item->grp])){
                echo "arbo.ajouterGroupe(groupe{$idPourGroupe});\n";
                
            //A déjà été ajouté ailleurs
            } else {
                // on note pour ne pas afficher les couches
                $tabSousGroupes[$item->grp] = $item->grp; 
                
            }
        }
    }

    //C'est une couche et on ne l'a pas déjà fait créer
    if ($item->type == "C" && !isset($tabCouchesAjoutees[$item->couche_id])) {
          
        //TODO Ajouter un commentaire...
        if (isset($tabSousGroupes[$item->id]) && $tabSousGroupes[$item->id] === $item->grp){
            //Ne pas afficher la couche
            continue;
        }
      
        $estVisible = $item->visible ? true : false;
        $estActif = $item->active ? true : false;
        $estCommune = $item->est_commune ? true : false;
        $associationEstAssociation = $estAdmin || $item->association_est_association;
        
        $attributs = array(
            'visible'=>array(
                'valeur'=>$estVisible, 
                'association' =>$associationEstAssociation
            ),
            'active'=>array(
                'valeur'=>$estActif, 
                'association' =>$associationEstAssociation
            ),
            'commune'=>array(
                'valeur'=>$estCommune,
                'association'=>''
            )
        );

        $url = ($estVisible || $estActif) ? $this->url->get('igo_couche_contexte/edit/') . $item->couche_contexte_id : '';
        $nom = $item->mf_layer_meta_group_title ? $item->mf_layer_meta_group_title : $item->nom;
        $nom = htmlentities($nom, ENT_QUOTES, 'UTF-8');
        
        $ordre = $item->layer_a_order ? $item->layer_a_order : '1';

        $idPourGroupe = Arborescence::idUniquePourGroupe($item->grp);
        $idPourCouche = $item->couche_id."_".$idPourGroupe;
        echo "var couche{$idPourCouche} = new Couche('{$idPourCouche}', '{$nom}', '{$url}', {$ordre}, ".json_encode($attributs).");\n";
        //Ajouter la couche dans le groupe
        echo "groupe{$idPourGroupe}.ajouterCouche(couche{$idPourCouche});\n";

        $tabCouchesAjoutees[$idPourCouche] = $idPourCouche;

    }

    //On a les informations sur une colonne
    if ($item->colonne) {

        $idColonne = $idPourCouche . '_' . $item->attribut_id;
        $estExclu = $item->exclu ? 'true' : 'false';

        echo "var colonne{$idColonne} = new Colonne('{$idColonne}', '{$item->colonne}', {$estExclu});\n";
        echo "couche{$idPourCouche}.ajouterColonne(colonne{$idColonne});\n";
    }
}
?>
    $(document).ready(function(){
        arbo.afficher();
        initComposantesArbo();
    });
    

    </script>
    </div>
    <div class="col-lg-2 col-md-2 conteneur-legende"> 
        <h3>Légende</h3>
        <ul>
            <li><span class="legende legende-visible"></span>Visible <span class="glyphicon glyphicon-question-sign"  data-toggle="tooltip" title="L'élément sera visible si cette case est cochée."></span></li>
            <li><span class="legende legende-active"></span>Actif <span class="glyphicon glyphicon-question-sign"  data-toggle="tooltip" title="L'élément sera actif si cette case est cochée."></span></li>
            <li><span class="legende legende-coche"></span>Coché <span class="glyphicon glyphicon-question-sign"  data-toggle="tooltip" title="L'élément est coché."></span></li>
            <li><span class="legende legende-partiel"></span>Partiel <span class="glyphicon glyphicon-question-sign"  data-toggle="tooltip" title="Au moins un des enfants de l'élément est coché."></span></li>
            <li><span class="legende legende-complet"></span>Complet <span class="glyphicon glyphicon-question-sign"  data-toggle="tooltip" title="Tous les enfants de l'élément sont cochés."></span></li>
            <li><span class="legende legende-partiel-gris"></span>Partiel grisé <span class="glyphicon glyphicon-question-sign"  data-toggle="tooltip" title="Au moins un des enfants de l'élément est coché. Cet élément ne sera pas visible dans l'arborescence cependant."></span></li>
            <li><span class="legende legende-complet-gris"></span>Complet grisé <span class="glyphicon glyphicon-question-sign"  data-toggle="tooltip" title="Tous les enfants de l'élément sont cochés. Cet élément ne sera pas visible dans l'arborescence cependant."></span></li>
            <li><span class="legende legende-exclu"></span>Exclu <span class="glyphicon glyphicon-question-sign"  data-toggle="tooltip" title="L'élément est exclu."></span></li>
        </ul>
    </div>
</div>