<?php use Phalcon\Tag; ?>
<?php echo $this->getContent(); ?>
<?php $this->partial("commun/titre", array("titre" =>"Associations contextes/couches")) ?>
<?php $this->partial("commun/search_entete") ?>

<table class="table table-striped table-search">
    <thead>
        <tr>
            <th class="id"><?php echo $this->tag->linkTo("igo_couche_contexte/$action?order=id", "Id<span class='glyphicon glyphicon-resize-vertical'></span>") ?></th>
            <th>Contexte</th>
            <th>Groupe de couches</th>
            <th>Couche</th>
            <th>Attribut exclu</th>
            <th class="est_visible">Visible</th>
            <th class="est_active">Active</th>
            <th>Mf Layer Meta Group Title</th>
            <th>Ordre</th>
            <th><?php echo $this->tag->linkTo("igo_couche_contexte/$action?order=date_modif", "Date de modification <span class='glyphicon glyphicon-resize-vertical'></span>") ?></th>
            <th class="editer"></th>
            <th class="detruire"></th> 
        </tr>
    </thead>
    <tbody>
    <?php foreach ($page->items as $igo_couche_contexte) { ?>
        <tr> 
            <td><?php  echo $igo_couche_contexte->id; ?></td>
            <td><?php  if ($igo_couche_contexte->IgoContexte) {echo $igo_couche_contexte->IgoContexte->nom;} ?></td>
            <td><?php  if ($igo_couche_contexte->IgoGroupe) {echo $igo_couche_contexte->IgoGroupe->nom;} ?></td>
            <td><?php  if ($igo_couche_contexte->IgoCouche) {echo $igo_couche_contexte->IgoCouche->mf_layer_name;} ?></td>
            <td><?php  if ($igo_couche_contexte->IgoAttribut){echo $igo_couche_contexte->IgoAttribut->colonne;} ?></td>
            <td>
                <?php if($igo_couche_contexte->est_visible):?>
                    <span class="glyphicon glyphicon-ok color-green"></span>
                <?php else:?>
                    <span class="glyphicon glyphicon-remove color-red"></span>
                <?php endif;?>
            </td>
             <td>
                <?php if($igo_couche_contexte->est_active):?>
                    <span class="glyphicon glyphicon-ok color-green"></span>
                <?php else:?>
                    <span class="glyphicon glyphicon-remove color-red"></span>
                <?php endif;?>
            </td>
            <td><!--php echo ($igo_couche_contexte->ind_fond_de_carte=="D" ||$igo_couche_contexte->ind_fond_de_carte=="" )?"Défaut": ($igo_couche_contexte->ind_fond_de_carte=="O"?"Oui":"Non") ?-->
            <?php  echo $igo_couche_contexte->mf_layer_meta_group_title; ?>
            </td>
            <td><?php echo $igo_couche_contexte->layer_a_order ?></td>
            <td><?php echo $igo_couche_contexte->date_modif ?></td>
            <td><?php echo $this->tag->linkTo(array("igo_couche_contexte/edit/" . $igo_couche_contexte->id."/".$r_controller."/".$action."/".$parameters, "<span class='glyphicon glyphicon-pencil' aria-hidden='true'></span> Modifier")); ?></td>
            <td><?php echo $this->tag->linkTo(array("igo_couche_contexte/delete/" . $igo_couche_contexte->id."/".$r_controller."/".$action."/".$parameters, "<span class='glyphicon glyphicon-trash' aria-hidden='true'></span> Détruire", 'data-confirmation'=>'supprimer')); ?></td>
        </tr>
    <?php } ?>
    </tbody>
</table>
<?php $this->partial("commun/search_pagination") ?>