<?php echo \Phalcon\Tag::javascriptInclude("js/gestion_couche_creation.js"); ?>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="contexte_id">Contexte<span class="glyphicon glyphicon-asterisk oblig"></span></label>
    </div>
    <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
        <?php
        echo $this->tag->select(array(
            "contexte_id",
            IgoContexte::find(array("order" => "nom")),
            "using" => array("id", "nom"),
            "emptyText" => "Choisir...",
            "useEmpty" => true,
            "class" => "form-control"
            ));
        ?>
    </div>
</div>
<div class="row">
     <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right"><label>Associer avec :</label> 
    </div>
    <div class="col-lg-4 col-md-5 col-sm-6 col-xs-12">
        <input type="radio" name="specifier" data-toggle="ligne_couche_id" id="specifier_couche" <?php  echo $this->view->estGroupeDeCouche ? 'checked': ''; ?>><label for="specifier_couche">Couche</label><br>
        <input type="radio" name="specifier" id="specifier_groupe_couche" <?php  echo !$this->view->estGroupeDeCouche ? 'checked': ''; ?>><label for="specifier_groupe_couche">Groupe de couche</label>
    </div>
</div>
<div class="row" data-toggle="specifier_couche">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="groupe_couche_id">Couche*</label>
    </div>
    <div class="col-lg-4 col-md-5 col-sm-6 col-xs-12">
        <?php
        echo $this->tag->select(array(
            "groupe_couche_id",
            $this->modelsManager->executeQuery('SELECT mf_layer_name, couche_id AS groupe_couche_id FROM IgoGroupeCouche AS gc INNER JOIN IgoCouche AS c ON c.id = gc.couche_id ORDER BY mf_layer_name'),
            "using" => array("groupe_couche_id", "mf_layer_name"),
            "emptyText" => "Choisir...",
            "useEmpty" => true,
            "class" => "form-control"
            ));
        ?>
    </div>
</div>
<div class="row" data-toggle="specifier_groupe_couche">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="groupe_couche_id">Groupe de couches*</label>
    </div>
    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
        <?php
        echo $this->tag->select(array(
            "groupe_id",
            IgoGroupe::find(array("order" => "nom")),
            "using" => array("id", "nom"),
            "emptyText" => "Choisir...",
            "useEmpty" => true,
            "class" => "form-control"
            ));
        ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="est_visible">Visible</label>
    </div>
    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
        <?php echo $this->tag->checkField(array("est_visible", "value" => 1)) ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="est_active">Active</label>
    </div>
    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
        <?php echo $this->tag->checkField(array("est_active", "value" => 1)) ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="ind_fond_de_carte">Indicateur Fond de Carte</label>
    </div>
    <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
        <?php
        echo $this->tag->select(array(
            "ind_fond_de_carte",
            array(
                "D" => "Défaut de la couche",
                "O" => "Oui",
                "N" => "Non"),
            "class" => "form-control"
            ));
        ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="mf_layer_meta_name">Mf Layer Meta Name</label>
    </div>
    <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
        <?php echo $this->tag->textField(array(
                "mf_layer_meta_name", 
                "class" => "form-control"
            ));
        ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="mf_layer_meta_title">Mf Layer Meta Title</label>
    </div>
    <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
        <?php echo $this->tag->textField(array(
                "mf_layer_meta_title", 
                "class" => "form-control"
            ));
        ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="mf_layer_meta_group_title">Mf Layer Meta Group Title</label>
    </div>
    <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
        <?php echo $this->tag->textField(array(
                "mf_layer_meta_group_title", 
                "class" => "form-control"
            ));
        ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="layer_a_order">Ordre A</label>
    </div>
    <div class="col-lg-2 col-md-3 col-sm-3 col-xs-12">
        <?php echo $this->tag->textField(array(
                "layer_a_order", 
                "class" => "form-control"
            ));
        ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="mf_layer_meta_z_order">Ordre Z</label>
    </div>
    <div class="col-lg-2 col-md-3 col-sm-3 col-xs-12">
        <?php echo $this->tag->textField(array(
                "mf_layer_meta_z_order", 
                "class" => "form-control"
            ));
        ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="mf_layer_class_def">Mf Layer Class Def</label>
    </div>
    <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
        <?php echo $this->tag->textField(array(
                "mf_layer_class_def", 
                "class" => "form-control"
            ));
        ?>
    </div>
</div>
<?php $this->partial("commun/date_modification"); ?>