<?php use Phalcon\Tag; ?>
<?php echo $this->getContent(); ?>
<?php $this->partial("commun/titre", array("titre" =>"Services")) ?>
<?php $this->partial("commun/search_entete") ?>

<table class="table table-striped table-search">
    <thead>
        <tr>
            <th class="id"><?php echo $this->tag->linkTo("igo_service/search?order=id", "Id<span class='glyphicon glyphicon-resize-vertical'></span>") ?></th>
            <th><?php echo $this->tag->linkTo("igo_service/search?order=nom", "Nom <span class='glyphicon glyphicon-resize-vertical'></span>") ?></th>
            <th><?php echo $this->tag->linkTo("igo_service/search?order=description", "Description <span class='glyphicon glyphicon-resize-vertical'></span>") ?></th>
            <th>WSDL</th>
            <th><?php echo $this->tag->linkTo("igo_service/search?order=date_modif", "Date de modification <span class='glyphicon glyphicon-resize-vertical'></span>") ?></th>
            <th class="editer"></th>
            <th class="detruire"></th>  
        </tr>
    </thead>
    <tbody>
    <?php foreach ($page->items as $igo_service) { ?>
        <tr>
            <td><?php echo $igo_service->id ?></td>
            <td><?php echo $igo_service->nom ?></td>
            <td><?php echo $igo_service->description ?></td>
            <td><?php echo $igo_service->wsdl ?></td>
            <td><?php echo $igo_service->date_modif ?></td>
            <td><?php echo $this->tag->linkTo(array("igo_service/edit/" . $igo_service->id."/".$r_controller."/".$action."/".$parameters, "<span class='glyphicon glyphicon-pencil' aria-hidden='true'></span> Modifier")); ?></td>
            <td><?php echo $this->tag->linkTo(array("igo_service/delete/" . $igo_service->id."/".$r_controller."/".$action."/".$parameters, "<span class='glyphicon glyphicon-trash' aria-hidden='true'></span> Détruire", 'data-confirmation'=>'supprimer')); ?></td>
        </tr>
    <?php } ?>
    </tbody>
</table>
<?php $this->partial("commun/search_pagination") ?>