<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="nom">Nom</label>
    </div>
    <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
        <?php echo $this->tag->textField(array(
                "nom", 
                "class" => "form-control"
            )); 
        ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="description">Description</label>
    </div>
    <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
        <?php echo $this->tag->textField(array(
                "description", 
                "class" => "form-control"
            )); 
        ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="wsdl">WSDL</label>
    </div>
    <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
        <?php echo $this->tag->textField(array(
                "wsdl", 
                "class" => "form-control"
            )); 
        ?>
    </div>
</div>
<?php $this->partial("commun/date_modification"); ?>