<?php if("edit" == $action || "save" == $action):?>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="date_modif">Date de modification</label>
    </div>
    <div class="col-lg-2 col-md-2 col-sm-3 col-xs-12">
        <?php
        echo $this->tag->textField(array(
            "date_modif",
            "class" => "form-control",
            'readonly' => 'readonly',
            'disabled' => 'disabled'));
        ?>
    </div>
</div>
<?php endif;?>