
<?php echo $this->getContent() ?>

<div class="row">
    <div class="col-lg-2 col-md-2 col-xs-2 text-left">
        <?php echo $this->tag->linkTo(array($retour, "<button type='button' class='btn btn-default'><span class='glyphicon glyphicon-share-alt glyphicon-retour'></span>Retour</button>")); ?>
    </div>
    <div class="col-lg-2 col-lg-offset-8 col-md-2 col-md-offset-8 col-xs-2 col-xs-offset-8 text-right">
        <?php echo $this->igo_tag->createButton(array($controller."/new"."/".$r_controller."/".$action."/".$parameters, "<button type='button' class='btn btn-default glyphicon glyphicon-plus'><span>Créer</span></button>"), $controller); ?>
    </div>
</div>

<?php echo $this->tag->form(array($controller . "/search", "autocomplete" => "off")) ?>

<div class="row">
    <div class="col-lg-8 col-lg-offset-4 col-md-8 col-md-offset-4 col-sm-8 col-sm-offset-4 col-xs-12 text-left">
        <h3><?php echo $titre ?></h3>
    </div>
</div>

<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
         <h4>Recherche par ID</h4>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="code">ID</label>
    </div>
    <div class="col-lg-2 col-md-3 col-sm-4 col-xs-12 text-left">
        <?php echo $this->tag->textField(array(
                "id", 
                "class"=>"form-control"
            ));
        ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <h4>ou par critères</h4>
    </div>
</div>
<?php $this->partial($controller . "/table") ?>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
    </div>
    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12 text-left">
        <?php echo $this->tag->submitButton(array("Rechercher", "class" => "btn btn-primary")) ?>
    </div>
</div>

<input type='hidden' id="r_parameters" name="r_parameters" value="<?php echo $parameters ?>"/>
</form>
