<?php echo \Phalcon\Tag::javascriptInclude("js/gestion_couche.js"); ?>
<script>
$(document).ready(function() {

    $('#acces').change(accesChange);
    $('#acces').triggerHandler('change');
});
</script>

<div class="row">
    <div class="col-lg-12  col-md-12 col-sm-12 col-xs-12 text-left">
         <?php echo $this->tag->linkTo(array($retour, "<button type='button' class='btn btn-default'><span class='glyphicon glyphicon-share-alt glyphicon-retour'></span>Retour</button>")); ?>
    </div>
</div>

<?php echo $this->getContent(); ?>

<?php $this->partial("commun/titre", array( "titre" =>$titre)) ?>

<?php echo $this->tag->form($controller . "/create/" . $retour) ?>

<?php $this->partial($controller . "/table") ?>
<div class="row">
    <div class="col-lg-8 col-lg-offset-4 col-md-8 col-md-offset-4 col-sm-8 col-xs-12 text-left">
        <?php echo $this->tag->submitButton(array("Enregistrer", 'class' => 'btn btn-primary')) ?>
    </div>
</div>


<input type='hidden' id="r_parameters" name="r_parameters" value="<?php echo $parameters ?>"/>
</form>
