<?php if ($page->total_pages > 1) { 
            $estPremierePage = $page->current == 1;
            $estDernierePage = ($page->total_pages == $page->current);
?>
<ul class="pager">
  <li class="<?php if($estPremierePage){echo 'disabled';} ?>"><?php echo $this->tag->linkTo($controller."/$action?page=1", "Premier") ?></li>
  <li class="<?php if($estPremierePage){echo 'disabled';} ?>"><?php echo $this->tag->linkTo($controller."/$action?page=" . $page->before, "Précédent") ?></li>
  <li>page <?php echo $page->current, " de ", $page->total_pages ?></li>
  <li class="<?php if($estDernierePage){echo 'disabled';} ?>"><?php echo $this->tag->linkTo($controller."/$action?page=" . ((!$estDernierePage)?$page->next:$page->current), "Suivant") ?></li>
  <li class="<?php if($estDernierePage){echo 'disabled';} ?>"><?php echo $this->tag->linkTo($controller."/$action?page=" . $page->last, "Dernier") ?></li>
</ul>
<?php } ?>