<style>
    .liste-contextes-a-regenerer th,
    .liste-contextes-a-regenerer td{
        padding:0.5em;
    }
</style>

<?php echo $this->getContent(); ?>

<div class="row">
    <div class="col-lg-8 col-lg-offset-4 col-md-8 col-md-offset-4 col-xs-12 text-left">
        <h3>Regénérer les contextes</h3>
    </div>
</div>

<?php if($igoContextes):?>

<div class="row">
    <div class="col-lg-8 col-lg-offset-4 col-md-8 col-md-offset-4 col-sm-8 col-xs-12 text-left">
        <?php echo $this->tag->submitButton(array("Lancer la mise à jour", "class" => "btn btn-primary", "id"=>'btn-regenerer')) ?>
    </div>
</div>
<br>
<section>
    <div id="statut-regeneration"></div>
    <h4>Contextes</h4>
    <table class="liste-contextes-a-regenerer">
        <thead>
            <tr>
                <th>Contexte</th>
                <th>Date de maj</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
        <?php foreach($igoContextes as $igoContexte):?>
        <tr data-igoContexte-id="<?php echo $igoContexte->id;?>">
            <td><?php echo $this->tag->linkTo(array("igo_contexte/edit/{$igoContexte->id}", "{$igoContexte->nom}({$igoContexte->code})", 'target'=>'_blank'));?></td>
            <td><span data-placeholder="data_maj"><?php echo $igoContexte->date_modif;?></span></td>
            <td><span data-placeholder="status"></span></td>
        </tr>

        <?php endforeach;?>
        </tbody>
    </table>
</section>
<?php else:?>
    <div class="alert alert-warning"><span class="glyphicon glyphicon-exclamation-sign"></span> Aucun contexte.</div>
<?php endif;?>  