<?php use Phalcon\Tag; ?>
<?php echo $this->getContent(); ?>
<?php $this->partial("commun/titre", array("titre" =>"Contextes")) ?>
<?php $this->partial("commun/search_entete") ?>

<style>
    .onlineressource{
        overflow:hidden; 
        white-space:nowrap; 
        text-overflow:ellipsis; 
        width:130px; 
        max-width:100px;
    }

</style>


<table class="table table-striped table-search">
    <thead>
        <tr>
            <th class="id"><?php echo $this->tag->linkTo("igo_contexte/search?order=id", "Id<span class='glyphicon glyphicon-resize-vertical'></span>") ?></th> 
            <th>Code</th>
            <th>Mode</th>
            <th><?php echo $this->tag->linkTo("igo_contexte/search?order=nom", "Nom <span class='glyphicon glyphicon-resize-vertical'></span>") ?></th>
            <th><?php echo $this->tag->linkTo("igo_contexte/search?order=description", "Description <span class='glyphicon glyphicon-resize-vertical'></span>") ?></th>
	    <th>Proprietaire ID</th>
            <th>Projection</th>
            <th class="onlineressource">Onlineresource</th>
            <th class="date_modif"><?php echo $this->tag->linkTo("igo_contexte/search?order=date_modif", "Date de modification <span class='glyphicon glyphicon-resize-vertical'></span>") ?></th>
            <th class="editer"></th>
            <th class="detruire"></th>
            <th class="associer"></th>
            <th class="editer"></th>
            <th class="mapfile"></th>
            <th class="voir"></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($page->items as $igo_contexte) { ?>
            <tr>
                <td><?php echo $igo_contexte->id ?></td>
                <td><?php echo $igo_contexte->code ?></td>
                <td><?php echo $igo_contexte->mode == "l" ? "Liste" : "Permission" ?></td>
                <td><?php echo $igo_contexte->nom ?></td>
                <td><?php echo $igo_contexte->description ?></td>
		<td><?php echo $igo_contexte->profil_proprietaire_id ?></td>
                <td><?php echo $igo_contexte->mf_map_projection ?></td>
                <td class="onlineressource" title="<?php echo $igo_contexte->mf_map_meta_onlineresource ?>"><?php echo $igo_contexte->mf_map_meta_onlineresource ?></td>
                <td><?php echo $igo_contexte->date_modif ?></td>
                <td><?php echo $this->igo_tag->linkIfProprietaire(array("igo_contexte/edit/" . $igo_contexte->id . "/" . $r_controller . "/" . $action . "/" . $parameters, "Editer"), $igo_contexte->profil_proprietaire_id); ?></td>
                <td><?php echo $this->igo_tag->linkIfProprietaire(array("igo_contexte/delete/" . $igo_contexte->id . "/" . $r_controller . "/" . $action . "/" . $parameters, "Détruire", 'data-confirmation'=>'supprimer'), $igo_contexte->profil_proprietaire_id); ?></td>
                <td><?php echo $this->tag->linkTo(array("igo_couche_contexte/arbreCouches/" . $igo_contexte->id, "Associer")); ?></td>
                <td><?php echo $this->tag->linkTo(array("contexte_et_couche/do/" . $igo_contexte->id, "Liste")); ?></td>
                <td><?php echo $this->tag->linkTo(array("igo_contexte/mapfile/" . $igo_contexte->id, "Mapfile")); ?></td>
                <td><?php echo $this->tag->linkTo(array($this->config->uri->navigateur .'contexte/' . $igo_contexte->id, "", "class" =>"glyphicon glyphicon-eye-open", "target"=>"_blank", 'local' =>FALSE)); ?></td>
            </tr>
        <?php } ?>
    </tbody>
</table>

<?php $this->partial("commun/search_pagination") ?>