<div id="search_entete" class="row">
    <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2 text-left">
        <?php echo $this->tag->linkTo(array($controller."/index"."/".$r_controller."/".$action."/".$parameters, "<button type='button' class='btn btn-default glyphicon glyphicon-search'><span>Rechercher</span></button>")); ?>
    </div>
    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-8">
        <?php 
            if (isset($criteres)){
            echo "Critères : ".$this->escaper->escapeHtml(str_replace("%","",$criteres)). "<br>".$this->tag->linkTo($controller."/searchAll", "<button type='button' class='btn btn-default glyphicon glyphicon-search'> <span>Rechercher tout</span></button>");
            }
        ?>
    </div>
    <div class="col-lg-2 col-md-2 col-sm-2 col-xs-2 text-right">
         <?php echo $this->igo_tag->createButton(array($controller."/new"."/".$r_controller."/".$action."/".$parameters, "<button type='button' class='btn btn-default glyphicon glyphicon-plus'><span>Créer/Dupliquer</span></button>"), $controller); ?>
    </div>
</div>