<?php
$estAdmin = $this->session->get("info_utilisateur")->estAdmin;
?>

<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="nom">Nom<span class="glyphicon glyphicon-asterisk oblig"></span></label>
    </div>
    <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
        <?php echo $this->tag->textField(array("nom", 
                "class" => "form-control"
            ));
        ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="profil_proprietaire_id">Profil propriétaire<?php if(!$estAdmin):?><span class="glyphicon glyphicon-asterisk oblig"></span><?php endif;?></label>
    </div>
    <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
        <?php
	    echo $this->tag->select(array(
				        "profil_proprietaire_id",
					IgoProfil::findAllProfils(),
					"using" => array("id", "libelle"),
					"emptyText" => "Choisir...",
					"useEmpty" => true,
					"class" => "form-control"
        				));
        ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="code">Code<span class="glyphicon glyphicon-asterisk oblig"></span></label>
    </div>
    <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
        <?php echo $this->tag->textField(array("code", 
                "class" => "form-control",
                "placeholder" => "Caractères acceptés : a-z et 0-9"
            ));
        ?>
    </div>
</div>

<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="description">Description</label>
    </div>
    <div class="col-lg-5 col-md-6 col-sm-7 col-xs-12">
        <?php echo $this->tag->textField(array("description", 
                "class" => "form-control"
            ));
        ?>
    </div>
</div>
<input type="hidden" name="mode" value="l">
<!--
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="mode">Mode<span class="glyphicon glyphicon-asterisk oblig"></span></label>
    </div>
    <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">

        <?php
        echo $this->tag->select(array(
            "mode",
            ($this->view->getActionName() == "index") ?
                    array(
                "" => " ",
                "l" => "Liste",
                "p" => "Permission") :
                    array(
                "l" => "Liste",
                "p" => "Permission"),
            "class" => "form-control"
            ));
        ?>
    </div>
</div>-->
<!--
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="position">Position</label>
    </div>
    <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
        <?php echo $this->tag->textField(array(
                "position", 
                "class" => "form-control"
            )); 
        ?>
    </div>
</div>
-->
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="zoom">Zoom</label>
    </div>
    <div class="col-lg-2 col-md-3 col-sm-3 col-xs-12">
        <?php echo $this->tag->textField(array(
                "zoom", 
                "type" => "number", 
                "class" => "form-control",
                "placeholder" => "Ex : 12,34"
            )); 
        ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="mf_map_def">Mf Map Def</label>
    </div>
    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
        <?php echo $this->tag->textArea(array(
                "mf_map_def", 
                "class" => "form-control",
                'cols' => 80, 
                'rows' => 5
            )); 
        ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="mf_map_projection">Projection</label><span class="glyphicon glyphicon-asterisk oblig"></span>
    </div>
    <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
        <?php echo $this->tag->textField(array(
                "mf_map_projection", 
                "type" => "number", 
                "class" => "form-control",
                "placeholder" => "Ex : 32198"
            )); 
        ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="mf_map_meta_onlineresource"><i>Online Resource</i></label><span class="glyphicon glyphicon-asterisk oblig"></span>
    </div>
    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">        
        <?php echo $this->tag->textField(array(
                "mf_map_meta_onlineresource", 
                "class" => "form-control"
            )); 
        ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-8 col-lg-offset-4 col-md-8 col-md-offset-4 col-sm-5 col-xs-12">        
        Vous pouvez insérer automatiquement le <i>Code</i> du contexte en utilisant le mot clé <b>{Code}</b>. Par ex : /cgi-wms/mapserv.fcgi?map={Code}.map
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="generer_onlineResource">Générer <i>Online Resource</i> dans le Mapfile</label>
    </div>
    <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">        
        <?php echo $this->tag->checkField(array(
                "generer_onlineresource",
                "value" => true
            )); 
        ?>
    </div>
</div>
<?php $this->partial("commun/date_modification"); ?>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="json">JSON</label>
    </div>
    <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
        <?php echo $this->tag->textField(array(
                "json", 
                "class" => "form-control"
            )); 
        ?>
    </div>
</div>
<?php
//Afficher seulement lors de la création d'un contexte
if('new' == $this->view->getActionName()):
?>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <h4>Fonctionalitées avancées</h4>
    </div>
    <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
       
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="json">Dupliquer les groupes et les couches de </label>
    </div>
    <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
          <?php
          
	    echo $this->tag->select(array(
				        "id_contexte_a_dupliquer",
					$igoContextesQuilPossede,
					"emptyText" => "Choisir...",
					"useEmpty" => true,
					"class" => "form-control"
        				));
        ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-8 col-lg-offset-4 col-md-8 col-md-offset-4 col-sm-5 col-xs-12">        
        Les groupes et les couches du contexte sélectionné seront automatiquement ajouté au nouveau contexte.
    </div>
</div>
<?php endif; ?>