<?php use Phalcon\Tag; ?>
<?php echo $this->getContent(); ?>
<?php $this->partial("commun/titre", array("titre" =>"Profils")) ?>
<?php $this->partial("commun/search_entete") ?>

<table class="table table-striped table-search">
    <thead>
        <tr>
            <th class="id"><?php echo $this->tag->linkTo("igo_profil/search?order=id", "Id<span class='glyphicon glyphicon-resize-vertical'></span>") ?></th>
            <th><?php echo $this->tag->linkTo("igo_profil/search?order=libelle", "Libellé <span class='glyphicon glyphicon-resize-vertical'></span>") ?></th>
            <th><?php echo $this->tag->linkTo("igo_profil/search?order=nom", "Nom <span class='glyphicon glyphicon-resize-vertical'></span>") ?></th>
            <th><?php echo $this->tag->linkTo("igo_profil/search?order=date_modif", "Date de modification <span class='glyphicon glyphicon-resize-vertical'></span>") ?></th>
	    <th>Propriétaire ID</th>
            <th class="editer"></th>
            <th class="detruire"></th>  
            <th class="associer"></th>
            <th class="permissions"></th>  
            <th class="utilisateurs"></th>
        </tr>
    </thead>
    <tbody>
<?php foreach ($page->items as $igo_profil) { ?>
             <tr>
                <td><?php echo $igo_profil->id ?></td>
                <td><?php echo $igo_profil->libelle ?></td>
                <td><?php echo $igo_profil->nom ?></td>
                <td><?php echo $igo_profil->date_modif ?></td>
		<td><?php echo $igo_profil->profil_proprietaire_id ?>
                <td><?php echo $this->igo_tag->linkIfProprietaire(array("igo_profil/edit/" . $igo_profil->id . "/" . $r_controller . "/" . $action . "/" . $parameters, "Editer"), $igo_profil->profil_proprietaire_id); ?></td>
                <td><?php echo $this->igo_tag->linkIfProprietaire(array("igo_profil/delete/" . $igo_profil->id."/".$r_controller."/".$action."/".$parameters, "Détruire", 'data-confirmation'=>'supprimer'), $igo_profil->profil_proprietaire_id); ?></td>
                <td><?php echo $this->igo_tag->linkIfProprietaire(array("igo_permission/arbreCouches/" . $igo_profil->id, "Associer"), $igo_profil->profil_proprietaire_id); ?></td>
                <td><?php echo $this->tag->linkTo(array("profil_et_permission/do/" . $igo_profil->id, "Permissions")); ?></td>
                <td><?php echo $this->tag->linkTo(array("profil_et_utilisateur/do/" . $igo_profil->id, "Utilisateurs")); ?></td>
            </tr>
    <?php } ?>
    </tbody>
</table>
<?php $this->partial("commun/search_pagination") ?>