<?php
$estAdmin = $this->session->get("info_utilisateur")->estAdmin;
?>

<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="libelle">Libellé<span class="glyphicon glyphicon-asterisk oblig"></span></label>
    </div>
    <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
        <?php echo $this->tag->textField(array(
                "libelle", 
                "class" => "form-control"
            )); 
        ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="nom">Nom<span class="glyphicon glyphicon-asterisk oblig"></span></label>
    </div>
    <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
        <?php echo $this->tag->textField(array(
                "nom", 
                "class" => "form-control"
            )); 
        ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="profil_proprietaire_id">Profil propriétaire<?php if(!$estAdmin):?><span class="glyphicon glyphicon-asterisk oblig"></span><?php endif;?></label>
    </div>
    <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
        <?php
	    echo $this->tag->select(array(
                                      "profil_proprietaire_id",
                                      IgoProfil::findAllProfils(),
                                      "using" => array("id", "libelle"),
                                      "emptyText" => "Choisir...",
                                      "useEmpty" => true,
                                      "class" => "form-control"
                                      ));
        ?>
    </div>
</div>
<?php $this->partial("commun/date_modification"); ?>