<?php

use Phalcon\Tag; ?>

<?php echo \Phalcon\Tag::javascriptInclude("js/arborescence/tree.js"); ?>
<?php echo \Phalcon\Tag::javascriptInclude("js/arborescence/util.js"); ?>
<?php echo \Phalcon\Tag::javascriptInclude("js/arborescence/Arborescence.js"); ?>
<?php echo \Phalcon\Tag::javascriptInclude("js/arborescence/Attribut.js"); ?>
<?php echo \Phalcon\Tag::javascriptInclude("js/arborescence/Attributs.js"); ?>
<?php echo \Phalcon\Tag::javascriptInclude("js/arborescence/Colonne.js"); ?>
<?php echo \Phalcon\Tag::javascriptInclude("js/arborescence/Couche.js"); ?>
<?php echo \Phalcon\Tag::javascriptInclude("js/arborescence/Groupe.js"); ?>
<?php echo \Phalcon\Tag::javascriptInclude("js/arborescence/ListeElement.js"); ?>

<?php echo \Phalcon\Tag::javascriptInclude("js/igo-permission-arbre-couche-edit.js"); ?>

<?php echo $this->getContent(); ?>

<?php echo $this->tag->form(array("/igo_permission/arbreCouches/" . $profil_id, 'id' => 'formArbo')); ?> 
<input type="hidden" id="valeursArbo" name="valeursArbo">

<?php $this->partial("commun/titre", array("titre" => "Donner des permissions à des groupes et des couches")) ?>

<div class="row">
    <div  class="col-lg-10 col-md-10">

        <ul class="pager">
            <li><input type="text" id="terme" placeholder="Filtre"><a href="#" id="ouvrirArborescence" class="btn btn-default navbar-btn" data-toggle="tooltip" title="Ouvre l'arborescence aux endroits correspondants au filtre">Ouvrir</a></li>
            <li><a href="#" id="fermerArborescence" class="btn btn-default navbar-btn" data-toggle="tooltip" title="Fermer l'arborescence">Fermer</a></li>
            <li><?php echo $this->tag->submitButton(array("Enregistrer", "class" => "btn btn-primary", "id" => "enregistrer")); ?></li>
        </ul>
    </div> 
</div>
</form> 

<div class="row text-left">
    <div  class="col-lg-10 col-md-10">
        <div id="conteneur-arborescence"><div id="arborescence"></div></div>
        <script>
            var arbo = new Arborescence({edition: false, estArboPermission:true});
<?php
$estAdmin = $this->session->get("info_utilisateur")->estAdmin;

$tabCouchesAjoutees = array();
$tabSousGroupes = array();

foreach ($arbre as $key => $item) {

    //Le groupe doit apparaître comem sous-groupe
    if ("G" == $item->type && strpos($item->grp, '_') !== false) {

        //Indiquer qu'il ne doit pas s'afficher à la racine
        $tabSousGroupes[$item->id] = true;
    }
}

foreach ($arbre as $key => $item) {

    //Pour les groupes et les couches
    $estLisible = $item->lecture ? true : false;
    $estAnalysable = $item->analyse_spa ? true : false;
    $estEcrivable = $item->ecriture ? true : false;
    $estExportable = $item->export ? true : false;
    $estAssociation = $item->association ? true : false;

    $lisibleEstAssociation = $estAdmin || $item->lecture_est_association;
    $analyseEstAssociation = $estAdmin || $item->analyse_est_association;
    $ecrivableEstAssociation = $estAdmin || $item->ecriture_est_association;
    $exportableEstAssociation = $estAdmin || $item->export_est_association;
    $associationEstAssociation = $estAdmin || $item->association_est_association;

    $attributs = array(
        'lecture' => array(
            'valeur' => $estLisible,
            'association' => $lisibleEstAssociation
        ),
        'analyse' => array(
            'valeur' => $estAnalysable,
            'association' => $analyseEstAssociation
        ),
        'ecriture' => array(
            'valeur' => $estEcrivable,
            'association' => $ecrivableEstAssociation
        ),
        'export' => array(
            'valeur' => $estExportable,
            'association' => $exportableEstAssociation
        ),
        'association' => array(
            'valeur' => $estAssociation,
            'association' => $associationEstAssociation
        )
    );


    if ($item->type == "G") {

        $url = ($estLisible || $estAnalysable || $estEcrivable || $estExportable || $estAssociation) ? $this->url->get('igo_permission/edit/') . $item->permission_id : '';
        $nom = htmlentities($item->nom, ENT_QUOTES, 'UTF-8');

        $ordre = isset($item->layer_a_order) ? $item->layer_a_order : '1';

        $idPourGroupe = $item->grp;
        $idParentPourGroupe = Arborescence::idUniquePourGroupeParent($item->grp);

        // On affiche les groupes uniquement si on est admin, où si on a les droits d'association dessus
        echo "var groupe{$idPourGroupe} = new Groupe('{$idPourGroupe}','{$item->id}_{$idPourGroupe}', '{$nom}', '{$url}', {$ordre}," . json_encode($attributs) . ");\n";

        //Le groupe n'est pas à la racine
        if (strpos($item->grp, '_') !== false) {

            echo "groupe{$idParentPourGroupe}.ajouterGroupe(groupe{$idPourGroupe});\n";

            //Le groupe est à la racine
        } else {

            //Ce n'est pas un sous-groupe et il n'a pas déjà été ajouté ailleurs
            if (!isset($tabSousGroupes[$item->id])) {
                echo "arbo.ajouterGroupe(groupe{$idPourGroupe});\n";

                //A déjà été ajouté ailleurs
            } else {
                // on note pour ne pas afficher les couches
                $tabSousGroupes[$item->id] = $item->grp;
            }
        }
    }

    //L'utilisateur à le droit d'associer cette couche
    if ($associationEstAssociation) {

        //C'est une couche et on ne l'a pas déjà fait créer
        if ($item->type == "C" && !isset($tabCouchesAjoutees[$item->couche_id])) {


            //TODO Ajouter un commentaire...
            if (isset($tabSousGroupes[$item->id]) && $tabSousGroupes[$item->id] === $item->grp) {
                //Ne pas afficher la couche
                continue;
            }


            $url = ($estLisible || $estAnalysable || $estEcrivable || $estExportable || $estAssociation) ? $this->url->get('igo_permission/edit/') . $item->permission_id : '';
            $nom = htmlentities($item->nom, ENT_QUOTES, 'UTF-8');

            $ordre = isset($item->layer_a_order) ? $item->layer_a_order : ($item->lecture?'1':'0');

            $idPourGroupe = Arborescence::idUniquePourGroupe($item->grp);
            $idPourCouche = $item->couche_id . "_" .$idPourGroupe; 
            echo "var couche{$idPourCouche} = new Couche('{$idPourCouche}', '{$nom}', '{$url}', {$ordre}, " . json_encode($attributs) . ");\n";
            //Ajouter la couche dans le groupe
            echo "groupe{$idPourGroupe}.ajouterCouche(couche{$idPourCouche});\n";

            $tabCouchesAjoutees[$idPourCouche] = $idPourCouche;
        }
    }

    if ($associationEstAssociation) {
        //On a les informations sur une colonne
        if ($item->colonne) {

            $idColonne = $idPourCouche . '_' . $item->attribut_id;
            $estExclu = $item->exclu ? 'true' : 'false';

            echo "var colonne{$idColonne} = new Colonne('{$idColonne}', '{$item->colonne}', {$estExclu});\n";
            echo "couche{$idPourCouche}.ajouterColonne(colonne{$idColonne});\n";
        }
    }
}
?>

        $(document).ready(function(){

            arbo.afficher();
            initComposantesArbo();
        });
        </script>

    </div>
    <div class="col-lg-2 col-md-2 conteneur-legende">
        <h3>Légende</h3>
        <ul>
            <li><span class="legende legende-lecture"></span>Lecture <span class="glyphicon glyphicon-question-sign"  data-toggle="tooltip" title="Le profil peut visualiser l'élément."></span></li>
            <li><span class="legende legende-analyse"></span>Analyse <span class="glyphicon glyphicon-question-sign"  data-toggle="tooltip" title="Le profil peut analyser l'élément."></span></li>
            <li><span class="legende legende-ecriture"></span>Écriture <span class="glyphicon glyphicon-question-sign"  data-toggle="tooltip" title="Le profil peut modifier l'élément."></span></li>
            <li><span class="legende legende-export"></span>Export <span class="glyphicon glyphicon-question-sign"  data-toggle="tooltip" title="Le profil peut exporter l'élément."></span></li>
            <li><span class="legende legende-association"></span>Association <span class="glyphicon glyphicon-question-sign"  data-toggle="tooltip" title="Le profil peut déléguer des permissions sur l'élément."></span></li>
            <li><span class="legende legende-coche"></span>Coché <span class="glyphicon glyphicon-question-sign"  data-toggle="tooltip" title="L'élément est coché."></span></li>
            <li><span class="legende legende-partiel"></span>Partiel <span class="glyphicon glyphicon-question-sign"  data-toggle="tooltip" title="Au moins un des enfants de l'élément est coché."></span></li>
            <li><span class="legende legende-complet"></span>Complet <span class="glyphicon glyphicon-question-sign"  data-toggle="tooltip" title="Tous les enfants de l'élément sont cochés."></span></li>
        </ul>
    </div>	
</div>
