
<?php echo $this->tag->stylesheetLink("css/bootstrap.css"); ?>
<?php echo $this->getContent(); ?>
<?php $this->flash->output() ?>
<?php echo $this->tag->form($controller."/save/".$retour) ?>

<table width="100%">
    <tr>
        <td align="left"><a href="javascript:window.close()" id="fermerArborescence" class="btn btn-default navbar-btn">Fermer</a></a></td>
       <!--td align="right"><php echo $this->tag->submitButton("Sauver") ></td-->
        <!--td align="right"><php echo $this->tag->linkTo(array($controller."/search", "Lister")) ></td-->
        
    <tr>
</table>

<?php $this->partial("commun/titre", array("titre" =>"Modifier une association profil/couche")) ?>

<table>
   <?php $this->partial($controller."/table") ?>

    <tr>
        <td><?php echo $this->tag->hiddenField("id") ?></td>
        <td><?php echo $this->tag->submitButton("Sauver") ?></td>
    </tr>
</table>

</form>

