<?php use Phalcon\Tag; ?>
<?php echo $this->getContent(); ?>
<?php $this->partial("commun/titre", array("titre" =>"Permissions sur les couches")) ?>
<?php $this->partial("commun/search_entete") ?>

<table class="table table-striped table-search">
    <thead>
        <tr>
            <th class="id"><?php echo $this->tag->linkTo("igo_permission/search?order=id", "Id<span class='glyphicon glyphicon-resize-vertical'></span>") ?></th>
            <th>Profil</th>
            <th>Groupe de couche</th>
            <th>Couche</th>
	    <th></th>
            <th class="est_lecture">Lecture</th>
            <th class="est_analyse">Analyse</th>
            <th class="est_ecriture">Écriture</th>
            <th class="est_exportation">Exportation</th>
	    <th>Association</th>
            <th><?php echo $this->tag->linkTo("igo_permission/search?order=date_modif", "Date de modification <span class='glyphicon glyphicon-resize-vertical'></span>") ?></th>
            <th class="editer"></th>
            <th class="detruire"></th>   
        </tr>
    </thead>
    <tbody>
        <?php foreach ($page->items as $igo_permission) { 
            ?>
        <tr>
            <td><?php echo $igo_permission->id ?></td>
            <td><?php if ($igo_permission->IgoProfil) {
                    echo $igo_permission->IgoProfil->libelle;
                } ?>
            </td>
            <td><?php 
                if ($igo_permission->IgoGroupe) {
                echo $igo_permission->IgoGroupe->nom;
                }else{
                    //echo $igo_permission->IgoGroupeCouche->IgoGroupe->nom;
                }
            ?>
            </td>
            <td>
	        <?php if ($igo_permission->IgoCouche) {
                    echo($igo_permission->IgoCouche->mf_layer_name);
            	} ?>
	    </td>
            <td><?php if ($igo_permission->IgoCouche) {
                if($igo_permission->IgoCouche->mf_layer_meta_title == ""){
                    echo "id:".$igo_permission->IgoCouche->id;
                }else{
                    echo $igo_permission->IgoCouche->mf_layer_meta_title;
                }
                
            } ?></td>
            <td>
                <?php if($igo_permission->est_lecture):?>
                    <span class="glyphicon glyphicon-ok color-green"></span>
                <?php else:?>
                    <span class="glyphicon glyphicon-remove color-red"></span>
                <?php endif;?>
            </td>  
            <td>
                <?php if($igo_permission->est_analyse):?>
                    <span class="glyphicon glyphicon-ok color-green"></span>
                <?php else:?>
                    <span class="glyphicon glyphicon-remove color-red"></span>
                <?php endif;?>
            </td>     
            <td>
                <?php if($igo_permission->est_ecriture):?>
                    <span class="glyphicon glyphicon-ok color-green"></span>
                <?php else:?>
                    <span class="glyphicon glyphicon-remove color-red"></span>
                <?php endif;?>
            </td>  
            <td>
                <?php if($igo_permission->est_export):?>
                    <span class="glyphicon glyphicon-ok color-green"></span>
                <?php else:?>
                    <span class="glyphicon glyphicon-remove color-red"></span>
                <?php endif;?>
            </td>    
            <td>
                <?php if($igo_permission->est_association):?>
                    <span class="glyphicon glyphicon-ok color-green"></span>
                <?php else:?>
                    <span class="glyphicon glyphicon-remove color-red"></span>
                <?php endif;?>
            </td>    
            <td><?php echo $igo_permission->date_modif ?></td>
            <td><?php echo $this->tag->linkTo(array("igo_permission/edit/" . $igo_permission->id . "/" . $r_controller . "/" . $action . "/" . $parameters, "<span class='glyphicon glyphicon-pencil' aria-hidden='true'></span> Modifier")); ?></td>
            <td><?php echo $this->tag->linkTo(array("igo_permission/delete/" . $igo_permission->id."/".$r_controller."/".$action."/".$parameters, "<span class='glyphicon glyphicon-trash' aria-hidden='true'></span> Détruire", 'data-confirmation'=>'supprimer')); ?></td>
        </tr>
        <?php } ?>
    </tbody>
</table>
<?php $this->partial("commun/search_pagination") ?>