<?php
$estAdmin = $this->session->get("info_utilisateur")->estAdmin;
?>

<?php echo \Phalcon\Tag::javascriptInclude("js/gestion_couche_creation.js"); ?>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="profil_id">Profil<?php if(!$estAdmin):?><span class="glyphicon glyphicon-asterisk oblig"></span><?php endif;?></label>
    </div>
    <div class="col-lg-4 col-md-5 col-sm-6 col-xs-12">  
        <?php
        echo $this->tag->select(array(
            "profil_id",
                $estAdmin ? IgoProfil::find(array("order" => "libelle")) : IgoProfil::findProfilsByProfilsProprietaires(),
                "using" => array("id", "libelle"),
                "emptyText" => "Choisir...",      
                "useEmpty" => true,
                "class" => "form-control"
                ));
        ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right"><label>Permission pour :</label> 
    </div>
    <div class="col-lg-4 col-md-5 col-sm-6 col-xs-12">
        <input type="radio" name="specifier" data-toggle="ligne_couche_id" id="specifier_couche" <?php  echo !$this->tag->getValue('groupe_id') ? 'checked': ''; ?>><label for="specifier_couche">Couche</label><br>
        <input type="radio" name="specifier" id="specifier_groupe_couche"<?php  echo $this->tag->getValue('groupe_id') ? 'checked': ''; ?>><label for="specifier_groupe_couche">Groupe de couche</label>
    </div>
</div>
<div class="row" data-toggle="specifier_couche">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="groupe_couche_id">Couche<span class="glyphicon glyphicon-asterisk oblig"></span></label>
    </div>
    <div class="col-lg-4 col-md-5 col-sm-6 col-xs-12">
        <?php
        echo $this->tag->select(array(
            "groupe_couche_id",
            $estAdmin ? IgoCouche::find() : IgoCouche::findEstAssociable(),
            "using" => array("id", "nom"),
            "emptyText" => "Choisir...",
            "useEmpty" => true,
            "class" => "form-control"
            ));
        ?>
    </div>
</div>
<div class="row" data-toggle="specifier_groupe_couche">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="groupe_id">Groupe de couches<span class="glyphicon glyphicon-asterisk oblig"></span></label>
    </div>
    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
        <?php
        echo $this->tag->select(array(
            "groupe_id",
            $estAdmin ? IgoGroupe::find() : IgoGroupe::findEstAssociable(),
            "using" => array("id", "nom"),
            "emptyText" => "Choisir...",
            "useEmpty" => true,
            "class" => "form-control"
            ));
        ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="est_lecture">Lecture</label>
    </div>
    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
        <?php echo $this->tag->checkField(array("est_lecture", "value" => 1)) ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="est_analyse">Analyse</label>
    </div>
    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
        <?php echo $this->tag->checkField(array("est_analyse", "value" => 1)) ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="est_ecriture">Écriture</label>
    </div>
    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
        <?php echo $this->tag->checkField(array("est_ecriture", "value" => 1)) ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="est_export">Exportation</label>
    </div>
    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
        <?php echo $this->tag->checkField(array("est_export", "value" => 1)) ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="est_association">Association</label>
    </div>
    <div class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
        <?php echo $this->tag->checkField(array("est_association", "value" => 1)) ?>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 text-right">
        <label for="mf_layer_filtre">Mf Layer Filtre</label>
    </div>
    <div class="col-lg-3 col-md-4 col-sm-5 col-xs-12">
        <?php echo $this->tag->textField(array(
                "mf_layer_filtre",
                "class" => "form-control"
            ));
        ?>
    </div>
</div>
<?php $this->partial("commun/date_modification"); ?>